type Query {
  user(id: ID!): User
  users(role: Role): [User!]!
  search(query: String!): [SearchItem!]!
  findUser(by: FindUserBy!): User
  post(id: ID!): Post
}

input FindUserBy @oneOf {
  id: ID
  email: String
}

type Mutation {
  createUser(input: CreateUserInput!): User!
}

type Subscription {
  postAdded(userId: ID!): Post!
}

enum Role {
  ADMIN
  MEMBER
}

interface Node {
  id: ID!
}

type User implements Node {
  id: ID!
  name: String!
  email: String!
  phone: String!
  role: Role!
  posts: [Post!]!
}

type Post implements Node {
  id: ID!
  title: String!
  body: String!
  author: User!
  attachment: Attachment
}

union SearchItem = User | Post

input CreateUserInput {
  name: String!
  email: String!
  role: Role!
}

union Attachment = ImageAttachment | LinkAttachment

type ImageAttachment {
  url: String!
  caption: String!
}

type LinkAttachment {
  href: String!
}
