from __future__ import annotations
# Code generated by iron_gql, DO NOT EDIT.
# fmt: off
# pyright: reportUnusedImport=false, reportUnsafeMultipleInheritance=false
# ruff: noqa


import datetime
import typing
from abc import ABC
from abc import abstractmethod
from collections.abc import AsyncGenerator
from collections.abc import Callable
from collections.abc import Sequence
from contextlib import AbstractAsyncContextManager
from typing import Annotated
from typing import Any
from typing import ClassVar
from typing import Literal
from typing import Never
from typing import TypeVar
from typing import final
from typing import overload
from typing import override

import pydantic

from iron_gql import runtime
from iron_gql import slots

import pydantic.alias_generators

import builtins

from example.config import GRAPHQL_URL


_client = runtime.AsyncGQLClient(
    base_url=GRAPHQL_URL,
)


class GQLModel(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True,
        serialize_by_alias=True,
        alias_generator=pydantic.AliasGenerator(
            validation_alias=pydantic.alias_generators.to_camel,
            serialization_alias=pydantic.alias_generators.to_camel,
        ),
        extra="forbid",
        validate_default=True,
    )


class GQLOpenModel(GQLModel):
    model_config = pydantic.ConfigDict(extra="ignore")


class GQLSlotModel[TOffered](GQLOpenModel, slots.GQLSlotNode[TOffered]):
    pass


type Role = Literal['ADMIN', 'MEMBER']


class PostWithIdTitle(GQLModel):
    id: builtins.str
    title: str


class UserWithEmailIdNamePhonePostsRole(GQLModel):
    id: builtins.str
    name: str
    email: str
    phone: str
    role: Role
    posts: list[PostWithIdTitle]


class GetUserResult(GQLModel):
    user: UserWithEmailIdNamePhonePostsRole | None


class UserWithName(GQLModel):
    name: str


class GetUserNameResult(GQLModel):
    user: UserWithName | None


class UserWithEmailIdNameRole(GQLModel):
    id: builtins.str
    name: str
    email: str
    role: Role


class CreateUserResult(GQLModel):
    create_user: UserWithEmailIdNameRole


class PostWithAuthorIdTitleTypename(GQLModel):
    typename__: Annotated[Literal["Post"], pydantic.Field(validation_alias="__typename", serialization_alias="__typename")]
    id: builtins.str
    title: str
    author: UserWithName


class UserWithIdNameRoleTypename(GQLModel):
    typename__: Annotated[Literal["User"], pydantic.Field(validation_alias="__typename", serialization_alias="__typename")]
    id: builtins.str
    name: str
    role: Role


type SearchResultSearch = Annotated[PostWithAuthorIdTitleTypename | UserWithIdNameRoleTypename, pydantic.Field(discriminator="typename__")]


class SearchResult(GQLModel):
    search: list[SearchResultSearch]


class PostWithIdTitleTypename(GQLModel):
    typename__: Annotated[Literal["Post"], pydantic.Field(validation_alias="__typename", serialization_alias="__typename")]
    id: builtins.str
    title: str


class UserWithIdNameTypename(GQLModel):
    typename__: Annotated[Literal["User"], pydantic.Field(validation_alias="__typename", serialization_alias="__typename")]
    id: builtins.str
    name: str


type GetNodeResultNode = Annotated[PostWithIdTitleTypename | UserWithIdNameTypename, pydantic.Field(discriminator="typename__")]


class GetNodeResult(GQLModel):
    node: GetNodeResultNode | None


class UserWithEmailIdNamePhoneRole(GQLModel):
    id: builtins.str
    name: str
    email: str | None = None
    phone: str | None = None
    role: Role


class GetProfileResult(GQLModel):
    user: UserWithEmailIdNamePhoneRole | None


class UserWithEmailIdName(GQLModel):
    id: builtins.str
    name: str
    email: str


class FindUserResult(GQLModel):
    find_user: UserWithEmailIdName | None


class PostWithCreatedAtIdTitle(GQLModel):
    id: builtins.str
    title: str
    created_at: datetime.datetime


class GetPostResult(GQLModel):
    post: PostWithCreatedAtIdTitle | None


class UserWithIdName(GQLModel):
    id: builtins.str
    name: str


class UploadAvatarResult(GQLModel):
    upload_avatar: UserWithIdName


class PostWithAuthorBodyIdTitle(GQLModel):
    id: builtins.str
    title: str
    body: str
    author: UserWithName


class PostAddedResult(GQLModel):
    post_added: PostWithAuthorBodyIdTitle


class PostAttachmentResultPostAttachmentSlotImageAttachment[TSlotAttachment = Never](GQLSlotModel[TSlotAttachment]):
    slot_name__: ClassVar[str] = "attachment"
    typename__: Annotated[Literal["ImageAttachment"], pydantic.Field(validation_alias="__typename", serialization_alias="__typename")]


class PostAttachmentResultPostAttachmentSlotLinkAttachment[TSlotAttachment = Never](GQLSlotModel[TSlotAttachment]):
    slot_name__: ClassVar[str] = "attachment"
    typename__: Annotated[Literal["LinkAttachment"], pydantic.Field(validation_alias="__typename", serialization_alias="__typename")]


type PostAttachmentResultPostAttachmentSlot[TSlotAttachment] = Annotated[PostAttachmentResultPostAttachmentSlotImageAttachment[TSlotAttachment] | PostAttachmentResultPostAttachmentSlotLinkAttachment[TSlotAttachment], pydantic.Field(discriminator="typename__")]


class PostWithAttachmentId_Opt_PostAttachmentResultPostAttachmentSlotID[TSlotAttachment = Never](GQLModel):
    id: builtins.str
    attachment: PostAttachmentResultPostAttachmentSlot[TSlotAttachment] | None


class PostAttachmentResult[TSlotAttachment = Never](GQLModel):
    post: PostWithAttachmentId_Opt_PostAttachmentResultPostAttachmentSlotID[TSlotAttachment] | None


class GetPostAttachmentResultPostAttachmentSlotImageAttachment[TSlotAttachment = Never](GQLSlotModel[TSlotAttachment]):
    slot_name__: ClassVar[str] = "attachment"
    typename__: Annotated[Literal["ImageAttachment"], pydantic.Field(validation_alias="__typename", serialization_alias="__typename")]


class GetPostAttachmentResultPostAttachmentSlotLinkAttachment[TSlotAttachment = Never](GQLSlotModel[TSlotAttachment]):
    slot_name__: ClassVar[str] = "attachment"
    typename__: Annotated[Literal["LinkAttachment"], pydantic.Field(validation_alias="__typename", serialization_alias="__typename")]


type GetPostAttachmentResultPostAttachmentSlot[TSlotAttachment] = Annotated[GetPostAttachmentResultPostAttachmentSlotImageAttachment[TSlotAttachment] | GetPostAttachmentResultPostAttachmentSlotLinkAttachment[TSlotAttachment], pydantic.Field(discriminator="typename__")]


class PostWithAttachmentId_Opt_GetPostAttachmentResultPostAttachmentSlotID[TSlotAttachment = Never](GQLModel):
    id: builtins.str
    attachment: GetPostAttachmentResultPostAttachmentSlot[TSlotAttachment] | None


class GetPostAttachmentResult[TSlotAttachment = Never](GQLModel):
    post: PostWithAttachmentId_Opt_GetPostAttachmentResultPostAttachmentSlotID[TSlotAttachment] | None


class ImageUrlData(GQLOpenModel):
    url: str


class LinkUrlData(GQLOpenModel):
    href: str


class ImageThumbnailData(GQLOpenModel):
    thumbnail: str


class CreateUserInput(GQLModel):
    name: str
    email: str
    role: Role


class FindUserById(GQLModel):
    id: builtins.str


class FindUserByEmail(GQLModel):
    email: str


type FindUserBy = FindUserById | FindUserByEmail


class GetUser(runtime.GQLOperation):
    # See: ch01_queries.py:5
    async def execute(self, *, id: builtins.str) -> GetUserResult:
        return await _client.query(
            GetUserResult,
            'query GetUser($id: ID!) {\n  user(id: $id) {\n    ...UserFields\n    posts {\n      id\n      title\n    }\n  }\n}\n\nfragment UserFields on User {\n  id\n  name\n  email\n  phone\n  role\n}',
            variables={"id": id},
            headers=self.headers,
        )


class GetUserName(runtime.GQLOperation):
    # See: ch01_queries.py:32
    async def execute(self, *, id: builtins.str) -> GetUserNameResult:
        return await _client.query(
            GetUserNameResult,
            'query GetUserName($id: ID!) {\n  user(id: $id) {\n    name\n  }\n}',
            variables={"id": id},
            headers=self.headers,
        )


class CreateUser(runtime.GQLOperation):
    # See: ch02_mutations.py:6
    async def execute(self, *, input: CreateUserInput) -> CreateUserResult:
        return await _client.query(
            CreateUserResult,
            'mutation CreateUser($input: CreateUserInput!) {\n  createUser(input: $input) {\n    id\n    name\n    email\n    role\n  }\n}',
            variables={"input": input},
            headers=self.headers,
        )


class Search(runtime.GQLOperation):
    # See: ch03_polymorphism.py:9
    async def execute(self, *, query: str) -> SearchResult:
        return await _client.query(
            SearchResult,
            'query Search($query: String!) {\n  search(query: $query) {\n    __typename\n    ... on User {\n      id\n      name\n      role\n    }\n    ... on Post {\n      id\n      title\n      author {\n        name\n      }\n    }\n  }\n}',
            variables={"query": query},
            headers=self.headers,
        )


class GetNode(runtime.GQLOperation):
    # See: ch03_polymorphism.py:36
    async def execute(self, *, id: builtins.str) -> GetNodeResult:
        return await _client.query(
            GetNodeResult,
            'query GetNode($id: ID!) {\n  node(id: $id) {\n    __typename\n    id\n    ... on User {\n      name\n    }\n    ... on Post {\n      title\n    }\n  }\n}',
            variables={"id": id},
            headers=self.headers,
        )


class GetProfile(runtime.GQLOperation):
    # See: ch04_variables.py:7
    async def execute(self, *, id: builtins.str, with_email: bool, skip_phone: bool) -> GetProfileResult:
        return await _client.query(
            GetProfileResult,
            'query GetProfile($id: ID!, $withEmail: Boolean!, $skipPhone: Boolean!) {\n  user(id: $id) {\n    id\n    name\n    email @include(if: $withEmail)\n    phone @skip(if: $skipPhone)\n    role\n  }\n}',
            variables={"id": id, "withEmail": with_email, "skipPhone": skip_phone},
            headers=self.headers,
        )


class FindUser(runtime.GQLOperation):
    # See: ch04_variables.py:30
    async def execute(self, *, by: FindUserBy) -> FindUserResult:
        return await _client.query(
            FindUserResult,
            'query FindUser($by: FindUserBy!) {\n  findUser(by: $by) {\n    id\n    name\n    email\n  }\n}',
            variables={"by": by},
            headers=self.headers,
        )


class GetPost(runtime.GQLOperation):
    # See: ch05_scalars.py:8
    async def execute(self, *, id: builtins.str) -> GetPostResult:
        return await _client.query(
            GetPostResult,
            'query GetPost($id: ID!) {\n  post(id: $id) {\n    id\n    title\n    createdAt\n  }\n}',
            variables={"id": id},
            headers=self.headers,
        )


class UploadAvatar(runtime.GQLOperation):
    # See: ch05_scalars.py:24
    async def execute(self, *, user_id: builtins.str, file: runtime.FileVar) -> UploadAvatarResult:
        return await _client.query(
            UploadAvatarResult,
            'mutation UploadAvatar($userId: ID!, $file: Upload!) {\n  uploadAvatar(userId: $userId, file: $file) {\n    id\n    name\n  }\n}',
            variables={"userId": user_id, "file": file},
            headers=self.headers,
        )


class PostAdded(runtime.GQLOperation):
    # See: ch07_subscriptions.py:5
    def execute(self, *, user_id: builtins.str) -> AbstractAsyncContextManager[AsyncGenerator[PostAddedResult]]:
        return _client.subscribe(
            PostAddedResult,
            'subscription PostAdded($userId: ID!) {\n  postAdded(userId: $userId) {\n    id\n    title\n    body\n    author {\n      name\n    }\n  }\n}',
            variables={"userId": user_id},
            headers=self.headers,
        )


TModel = TypeVar("TModel", bound=pydantic.BaseModel, covariant=True)
TReads = TypeVar("TReads", contravariant=True)


class OnImageAttachment(slots.GQLBindableFragment[TModel, TReads], ABC):
    @abstractmethod
    def __init__(
        self,
        *,
        fragment_name: str,
        definition_type: type[slots.GQLFragment[
            TModel, TReads,
        ]],
        adapter: pydantic.TypeAdapter[TModel],
    ) -> None:
        super().__init__(
            fragment_name=fragment_name,
            definition_type=definition_type,
            adapter=adapter,
        )


class OnLinkAttachment(slots.GQLBindableFragment[TModel, TReads], ABC):
    @abstractmethod
    def __init__(
        self,
        *,
        fragment_name: str,
        definition_type: type[slots.GQLFragment[
            TModel, TReads,
        ]],
        adapter: pydantic.TypeAdapter[TModel],
    ) -> None:
        super().__init__(
            fragment_name=fragment_name,
            definition_type=definition_type,
            adapter=adapter,
        )


@final
class ImageUrl(OnImageAttachment[ImageUrlData, "ImageUrl"]):
    adapter__: ClassVar[pydantic.TypeAdapter[ImageUrlData]] = pydantic.TypeAdapter(ImageUrlData)

    @override
    def __init__(self) -> None:
        super().__init__(
            fragment_name='ImageUrl',
            definition_type=ImageUrl,
            adapter=self.adapter__,
        )


@final
class LinkUrl(OnLinkAttachment[LinkUrlData, "LinkUrl"]):
    adapter__: ClassVar[pydantic.TypeAdapter[LinkUrlData]] = pydantic.TypeAdapter(LinkUrlData)

    @override
    def __init__(self) -> None:
        super().__init__(
            fragment_name='LinkUrl',
            definition_type=LinkUrl,
            adapter=self.adapter__,
        )


@final
class ImageThumbnail(slots.GQLFragment[ImageThumbnailData, "_ImageThumbnailApplied"]):
    adapter__: ClassVar[pydantic.TypeAdapter[ImageThumbnailData]] = pydantic.TypeAdapter(ImageThumbnailData)

    @override
    def __init__(self) -> None:
        super().__init__(
            fragment_name='ImageThumbnail',
            definition_type=ImageThumbnail,
            adapter=self.adapter__,
        )

    def with_args(self, *, width: int) -> _ImageThumbnailApplied:
        return _ImageThumbnailApplied({"width": width})


@final
class _ImageThumbnailApplied(OnImageAttachment[ImageThumbnailData, "_ImageThumbnailApplied"]):
    @override
    def __init__(self, fragment_args: dict[str, object], /) -> None:
        super().__init__(
            fragment_name='ImageThumbnail',
            definition_type=ImageThumbnail,
            adapter=ImageThumbnail.adapter__,
        )
        self._set_fragment_args(fragment_args)


class PostAttachmentBound[TResult: pydantic.BaseModel](runtime.GQLBoundOperation):
    async def execute(self, *, id: builtins.str) -> TResult:
        return await _client.query(
            typing.cast("type[TResult]", PostAttachmentResult),
            self.exec_source,
            variables={"id": id, **self.fragment_args},
            headers=self.headers,
            slot_readers=self.slot_readers,
        )


class GetPostAttachmentBound[TResult: pydantic.BaseModel](runtime.GQLBoundOperation):
    async def execute(self, *, id: builtins.str) -> TResult:
        return await _client.query(
            typing.cast("type[TResult]", GetPostAttachmentResult),
            self.exec_source,
            variables={"id": id, **self.fragment_args},
            headers=self.headers,
            slot_readers=self.slot_readers,
        )


class PostAttachment(runtime.GQLTemplate):
    _binding_specs: ClassVar[dict[slots.BindingKey, runtime.BoundSpec]] = {
        # See: ch06_slots.py:10
        (): ('query PostAttachment($id: ID!) {\n  post(id: $id) {\n    id\n    attachment {\n      __typename\n    }\n  }\n}', {"attachment": ()}),
        # See: ch06_slots.py:10, ch06_slots.py:53
        (('attachment', (_ImageThumbnailApplied,)),): ('query PostAttachment($id: ID!, $width: Int!) {\n  post(id: $id) {\n    id\n    attachment {\n      __typename\n      ...ImageThumbnail\n    }\n  }\n}\n\nfragment ImageThumbnail on ImageAttachment {\n  thumbnail(width: $width)\n}', {"attachment": ((ImageThumbnail, frozenset({'ImageAttachment'})),)}),
        # See: ch06_slots.py:10, ch06_slots.py:41
        (('attachment', (ImageUrl,)),): ('query PostAttachment($id: ID!) {\n  post(id: $id) {\n    id\n    attachment {\n      __typename\n      ...ImageUrl\n    }\n  }\n}\n\nfragment ImageUrl on ImageAttachment {\n  url\n}', {"attachment": ((ImageUrl, frozenset({'ImageAttachment'})),)}),
        # See: ch06_slots.py:10, ch06_slots.py:47
        (('attachment', (LinkUrl,)),): ('query PostAttachment($id: ID!) {\n  post(id: $id) {\n    id\n    attachment {\n      __typename\n      ...LinkUrl\n    }\n  }\n}\n\nfragment LinkUrl on LinkAttachment {\n  href\n}', {"attachment": ((LinkUrl, frozenset({'LinkAttachment'})),)}),
    }

    @overload
    def bind(self, *, attachment: Sequence[Never] = ()) -> PostAttachmentBound[PostAttachmentResult[Never]]: ...
    @overload
    def bind[TModelAttachment: pydantic.BaseModel, TReadsAttachment](self, *, attachment: OnImageAttachment[TModelAttachment, TReadsAttachment]) -> PostAttachmentBound[PostAttachmentResult[OnImageAttachment[TModelAttachment, TReadsAttachment] | TReadsAttachment]]: ...
    @overload
    def bind[TModelAttachment: pydantic.BaseModel, TReadsAttachment](self, *, attachment: OnLinkAttachment[TModelAttachment, TReadsAttachment]) -> PostAttachmentBound[PostAttachmentResult[OnLinkAttachment[TModelAttachment, TReadsAttachment] | TReadsAttachment]]: ...
    def bind(self, *, attachment: slots.GQLBindableFragment[pydantic.BaseModel, Any] | Sequence[slots.GQLBindableFragment[pydantic.BaseModel, Any]] = ()) -> runtime.GQLBoundOperation:
        if slots.binding_key({'attachment': attachment}) not in self._binding_specs:
            raise LookupError("unknown bind combination for PostAttachment; single-fragment and empty combinations are generated from the schema, so this is a tuple combination no call site writes literally - write it, then regenerate the package. A call whose template is an expression the scan cannot follow is never read either: those are listed, with the reason, in the debug run's ignored_binds.json")
        return PostAttachmentBound[PostAttachmentResult].bound__(
            self._binding_specs[slots.binding_key({'attachment': attachment})], {'attachment': slots.as_bindable_fragments(attachment)},
        )


class GetPostAttachment(runtime.GQLTemplate):
    _binding_specs: ClassVar[dict[slots.BindingKey, runtime.BoundSpec]] = {
        # See: ch06_slots.py:32
        (): ('query GetPostAttachment($id: ID!) {\n  post(id: $id) {\n    id\n    attachment {\n      __typename\n    }\n  }\n}', {"attachment": ()}),
        # See: ch06_slots.py:32, ch06_slots.py:53
        (('attachment', (_ImageThumbnailApplied,)),): ('query GetPostAttachment($id: ID!, $width: Int!) {\n  post(id: $id) {\n    id\n    attachment {\n      __typename\n      ...ImageThumbnail\n    }\n  }\n}\n\nfragment ImageThumbnail on ImageAttachment {\n  thumbnail(width: $width)\n}', {"attachment": ((ImageThumbnail, frozenset({'ImageAttachment'})),)}),
        # See: ch06_slots.py:32, ch06_slots.py:41
        (('attachment', (ImageUrl,)),): ('query GetPostAttachment($id: ID!) {\n  post(id: $id) {\n    id\n    attachment {\n      __typename\n      ...ImageUrl\n    }\n  }\n}\n\nfragment ImageUrl on ImageAttachment {\n  url\n}', {"attachment": ((ImageUrl, frozenset({'ImageAttachment'})),)}),
        # See: ch06_slots.py:32, ch06_slots.py:47
        (('attachment', (LinkUrl,)),): ('query GetPostAttachment($id: ID!) {\n  post(id: $id) {\n    id\n    attachment {\n      __typename\n      ...LinkUrl\n    }\n  }\n}\n\nfragment LinkUrl on LinkAttachment {\n  href\n}', {"attachment": ((LinkUrl, frozenset({'LinkAttachment'})),)}),
        # See: ch06_slots.py:59
        (('attachment', (ImageUrl, LinkUrl)),): ('query GetPostAttachment($id: ID!) {\n  post(id: $id) {\n    id\n    attachment {\n      __typename\n      ...ImageUrl\n      ...LinkUrl\n    }\n  }\n}\n\nfragment ImageUrl on ImageAttachment {\n  url\n}\n\nfragment LinkUrl on LinkAttachment {\n  href\n}', {"attachment": ((ImageUrl, frozenset({'ImageAttachment'})), (LinkUrl, frozenset({'LinkAttachment'})))}),
    }

    @overload
    def bind(self, *, attachment: Sequence[Never] = ()) -> GetPostAttachmentBound[GetPostAttachmentResult[Never]]: ...
    @overload
    def bind[TModelAttachment: pydantic.BaseModel, TReadsAttachment](self, *, attachment: OnImageAttachment[TModelAttachment, TReadsAttachment]) -> GetPostAttachmentBound[GetPostAttachmentResult[OnImageAttachment[TModelAttachment, TReadsAttachment] | TReadsAttachment]]: ...
    @overload
    def bind[TModelAttachment: pydantic.BaseModel, TReadsAttachment](self, *, attachment: OnLinkAttachment[TModelAttachment, TReadsAttachment]) -> GetPostAttachmentBound[GetPostAttachmentResult[OnLinkAttachment[TModelAttachment, TReadsAttachment] | TReadsAttachment]]: ...
    @overload
    def bind[TFillAttachment1: (ImageUrl, LinkUrl), TFillAttachment2: (ImageUrl, LinkUrl)](self, *, attachment: tuple[TFillAttachment1, TFillAttachment2]) -> GetPostAttachmentBound[GetPostAttachmentResult[TFillAttachment1 | TFillAttachment2]]: ...
    def bind(self, *, attachment: slots.GQLBindableFragment[pydantic.BaseModel, Any] | Sequence[slots.GQLBindableFragment[pydantic.BaseModel, Any]] = ()) -> runtime.GQLBoundOperation:
        if slots.binding_key({'attachment': attachment}) not in self._binding_specs:
            raise LookupError("unknown bind combination for GetPostAttachment; single-fragment and empty combinations are generated from the schema, so this is a tuple combination no call site writes literally - write it, then regenerate the package. A call whose template is an expression the scan cannot follow is never read either: those are listed, with the reason, in the debug run's ignored_binds.json")
        return GetPostAttachmentBound[GetPostAttachmentResult].bound__(
            self._binding_specs[slots.binding_key({'attachment': attachment})], {'attachment': slots.as_bindable_fragments(attachment)},
        )


@overload
def api_gql(stmt: Literal['\n        query GetUser($id: ID!) {\n            user(id: $id) {\n                ...UserFields\n                posts { id title }\n            }\n        }\n\n        fragment UserFields on User {\n            id\n            name\n            email\n            phone\n            role\n        }\n    ']) -> GetUser: ...
@overload
def api_gql(stmt: Literal['\n        query GetUserName($id: ID!) {\n            user(id: $id) {\n                name\n            }\n        }\n    ']) -> GetUserName: ...
@overload
def api_gql(stmt: Literal['\n        mutation CreateUser($input: CreateUserInput!) {\n            createUser(input: $input) {\n                id\n                name\n                email\n                role\n            }\n        }\n    ']) -> CreateUser: ...
@overload
def api_gql(stmt: Literal['\n        query Search($query: String!) {\n            search(query: $query) {\n                __typename\n                ... on User {\n                    id\n                    name\n                    role\n                }\n                ... on Post {\n                    id\n                    title\n                    author { name }\n                }\n            }\n        }\n    ']) -> Search: ...
@overload
def api_gql(stmt: Literal['\n        query GetNode($id: ID!) {\n            node(id: $id) {\n                __typename\n                id\n                ... on User { name }\n                ... on Post { title }\n            }\n        }\n    ']) -> GetNode: ...
@overload
def api_gql(stmt: Literal['\n        query GetProfile($id: ID!, $withEmail: Boolean!, $skipPhone: Boolean!) {\n            user(id: $id) {\n                id\n                name\n                email @include(if: $withEmail)\n                phone @skip(if: $skipPhone)\n                role\n            }\n        }\n    ']) -> GetProfile: ...
@overload
def api_gql(stmt: Literal['\n        query FindUser($by: FindUserBy!) {\n            findUser(by: $by) {\n                id\n                name\n                email\n            }\n        }\n    ']) -> FindUser: ...
@overload
def api_gql(stmt: Literal['\n        query GetPost($id: ID!) {\n            post(id: $id) {\n                id\n                title\n                createdAt\n            }\n        }\n    ']) -> GetPost: ...
@overload
def api_gql(stmt: Literal['\n            mutation UploadAvatar($userId: ID!, $file: Upload!) {\n                uploadAvatar(userId: $userId, file: $file) {\n                    id\n                    name\n                }\n            }\n        ']) -> UploadAvatar: ...
@overload
def api_gql(stmt: Literal['\n        subscription PostAdded($userId: ID!) {\n            postAdded(userId: $userId) {\n                id\n                title\n                body\n                author { name }\n            }\n        }\n    ']) -> PostAdded: ...
@overload
def api_gql(stmt: Literal['\n        fragment ImageUrl on ImageAttachment {\n            url\n        }\n    ']) -> ImageUrl: ...
@overload
def api_gql(stmt: Literal['\n        fragment LinkUrl on LinkAttachment {\n            href\n        }\n    ']) -> LinkUrl: ...
@overload
def api_gql(stmt: Literal['\n        fragment ImageThumbnail on ImageAttachment {\n            thumbnail(width: $width)\n        }\n    ']) -> ImageThumbnail: ...
@overload
def api_gql(stmt: Literal['\n    query PostAttachment($id: ID!) {\n        post(id: $id) {\n            id\n            attachment @slot { __typename }\n        }\n    }\n']) -> PostAttachment: ...
@overload
def api_gql(stmt: Literal['\n        query GetPostAttachment($id: ID!) {\n            post(id: $id) {\n                id\n                attachment @slot { __typename }\n            }\n        }\n    ']) -> GetPostAttachment: ...
@overload
def api_gql(stmt: str) -> runtime.GQLOperation | slots.GQLFragment[pydantic.BaseModel, Any] | runtime.GQLTemplate: ...


_statement_factories: dict[str, Callable[[], runtime.GQLOperation | slots.GQLFragment[pydantic.BaseModel, Any] | runtime.GQLTemplate]] = {
    '\n        query GetUser($id: ID!) {\n            user(id: $id) {\n                ...UserFields\n                posts { id title }\n            }\n        }\n\n        fragment UserFields on User {\n            id\n            name\n            email\n            phone\n            role\n        }\n    ': GetUser,
    '\n        query GetUserName($id: ID!) {\n            user(id: $id) {\n                name\n            }\n        }\n    ': GetUserName,
    '\n        mutation CreateUser($input: CreateUserInput!) {\n            createUser(input: $input) {\n                id\n                name\n                email\n                role\n            }\n        }\n    ': CreateUser,
    '\n        query Search($query: String!) {\n            search(query: $query) {\n                __typename\n                ... on User {\n                    id\n                    name\n                    role\n                }\n                ... on Post {\n                    id\n                    title\n                    author { name }\n                }\n            }\n        }\n    ': Search,
    '\n        query GetNode($id: ID!) {\n            node(id: $id) {\n                __typename\n                id\n                ... on User { name }\n                ... on Post { title }\n            }\n        }\n    ': GetNode,
    '\n        query GetProfile($id: ID!, $withEmail: Boolean!, $skipPhone: Boolean!) {\n            user(id: $id) {\n                id\n                name\n                email @include(if: $withEmail)\n                phone @skip(if: $skipPhone)\n                role\n            }\n        }\n    ': GetProfile,
    '\n        query FindUser($by: FindUserBy!) {\n            findUser(by: $by) {\n                id\n                name\n                email\n            }\n        }\n    ': FindUser,
    '\n        query GetPost($id: ID!) {\n            post(id: $id) {\n                id\n                title\n                createdAt\n            }\n        }\n    ': GetPost,
    '\n            mutation UploadAvatar($userId: ID!, $file: Upload!) {\n                uploadAvatar(userId: $userId, file: $file) {\n                    id\n                    name\n                }\n            }\n        ': UploadAvatar,
    '\n        subscription PostAdded($userId: ID!) {\n            postAdded(userId: $userId) {\n                id\n                title\n                body\n                author { name }\n            }\n        }\n    ': PostAdded,
    '\n        fragment ImageUrl on ImageAttachment {\n            url\n        }\n    ': lambda: ImageUrl(),
    '\n        fragment LinkUrl on LinkAttachment {\n            href\n        }\n    ': lambda: LinkUrl(),
    '\n        fragment ImageThumbnail on ImageAttachment {\n            thumbnail(width: $width)\n        }\n    ': lambda: ImageThumbnail(),
    '\n    query PostAttachment($id: ID!) {\n        post(id: $id) {\n            id\n            attachment @slot { __typename }\n        }\n    }\n': PostAttachment,
    '\n        query GetPostAttachment($id: ID!) {\n            post(id: $id) {\n                id\n                attachment @slot { __typename }\n            }\n        }\n    ': GetPostAttachment,
}


def api_gql(stmt: str) -> runtime.GQLOperation | slots.GQLFragment[pydantic.BaseModel, Any] | runtime.GQLTemplate:
    if stmt not in _statement_factories:
        msg = "unknown GraphQL statement passed to api_gql; "
        msg += "the generator only discovers bare-name calls with a "
        msg += "single string literal - check the call site, then "
        msg += "regenerate the package"
        raise LookupError(msg)
    return _statement_factories[stmt]()
