from __future__ import annotations
# Code generated by iron_gql, DO NOT EDIT.
# fmt: off
# pyright: reportUnusedImport=false, reportUnsafeMultipleInheritance=false
# ruff: noqa


import datetime
from collections.abc import AsyncGenerator
from collections.abc import Sequence
from contextlib import AbstractAsyncContextManager
from typing import Annotated
from typing import ClassVar
from typing import Literal
from typing import overload

import pydantic

from iron_gql import runtime
from iron_gql import slots

import pydantic.alias_generators

import builtins

from example.config import GRAPHQL_URL


API_CLIENT = runtime.GQLClient(
    base_url=GRAPHQL_URL,
)


class GQLModel(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True,
        serialize_by_alias=True,
        alias_generator=pydantic.AliasGenerator(
            validation_alias=pydantic.alias_generators.to_camel,
            serialization_alias=pydantic.alias_generators.to_camel,
        ),
        extra="forbid",
        validate_default=True,
    )


class GQLOpenModel(GQLModel):
    model_config = pydantic.ConfigDict(extra="ignore")


class GQLSlotModel(GQLOpenModel, slots.GQLSlotNode):
    pass


class AttachmentFragment[TModel: pydantic.BaseModel](slots.GQLFragment[TModel]): ...


type Role = Literal['ADMIN', 'MEMBER']


class GetPostAttachmentResultPostAttachmentSlotImageAttachment(GQLSlotModel):
    slot_name__: ClassVar[str] = "attachment"
    typename__: Annotated[Literal["ImageAttachment"], pydantic.Field(validation_alias="__typename", serialization_alias="__typename")]


class GetPostAttachmentResultPostAttachmentSlotLinkAttachment(GQLSlotModel):
    slot_name__: ClassVar[str] = "attachment"
    typename__: Annotated[Literal["LinkAttachment"], pydantic.Field(validation_alias="__typename", serialization_alias="__typename")]


type GetPostAttachmentResultPostAttachmentSlot = Annotated[GetPostAttachmentResultPostAttachmentSlotImageAttachment | GetPostAttachmentResultPostAttachmentSlotLinkAttachment, pydantic.Field(discriminator="typename__")]


class PostWithAttachmentId(GQLModel):
    id: builtins.str
    attachment: GetPostAttachmentResultPostAttachmentSlot | None


class GetPostAttachmentResult(GQLModel):
    post: PostWithAttachmentId | None


class PostWithIdTitle(GQLModel):
    id: builtins.str
    title: str


class UserWithEmailIdNamePhonePostsRole(GQLModel):
    id: builtins.str
    name: str
    email: str
    phone: str
    role: Role
    posts: list[PostWithIdTitle]


class GetUserResult(GQLModel):
    user: UserWithEmailIdNamePhonePostsRole | None


class UserWithEmailIdNameRole(GQLModel):
    id: builtins.str
    name: str
    email: str
    role: Role


class CreateUserResult(GQLModel):
    create_user: UserWithEmailIdNameRole


class UserWithName(GQLModel):
    name: str


class PostWithAuthorIdTitleTypename(GQLModel):
    typename__: Annotated[Literal["Post"], pydantic.Field(validation_alias="__typename", serialization_alias="__typename")]
    id: builtins.str
    title: str
    author: UserWithName


class UserWithIdNameRoleTypename(GQLModel):
    typename__: Annotated[Literal["User"], pydantic.Field(validation_alias="__typename", serialization_alias="__typename")]
    id: builtins.str
    name: str
    role: Role


type SearchResultSearch = Annotated[PostWithAuthorIdTitleTypename | UserWithIdNameRoleTypename, pydantic.Field(discriminator="typename__")]


class SearchResult(GQLModel):
    search: list[SearchResultSearch]


class UserWithEmailIdNamePhoneRole(GQLModel):
    id: builtins.str
    name: str
    email: str | None = None
    phone: str | None = None
    role: Role


class GetProfileResult(GQLModel):
    user: UserWithEmailIdNamePhoneRole | None


class UserWithEmailIdName(GQLModel):
    id: builtins.str
    name: str
    email: str


class FindUserResult(GQLModel):
    find_user: UserWithEmailIdName | None


class PostWithAuthorBodyIdTitle(GQLModel):
    id: builtins.str
    title: str
    body: str
    author: UserWithName


class PostAddedResult(GQLModel):
    post_added: PostWithAuthorBodyIdTitle


class ImageUrlData(GQLOpenModel):
    url: str


class CreateUserInput(GQLModel):
    name: str
    email: str
    role: Role


class FindUserById(GQLModel):
    id: builtins.str


class FindUserByEmail(GQLModel):
    email: str


type FindUserBy = FindUserById | FindUserByEmail


class GetPostAttachment(runtime.GQLOperation):
    # See: main.py:25
    async def execute(self, *, id: builtins.str, attachment: AttachmentFragment[pydantic.BaseModel] | Sequence[AttachmentFragment[pydantic.BaseModel]]) -> GetPostAttachmentResult:
        slot_fragments = {"attachment": slots.as_handles(attachment)}
        return await API_CLIENT.query(
            GetPostAttachmentResult,
            slots.build_slot_source('query GetPostAttachment($id: ID!) {\n  post(id: $id) {\n    id\n    attachment {\n      __typename\n      ', (('attachment', '\n    }\n  }\n}'),), slot_fragments),
            variables={"id": id},
            headers=self.headers,
            slot_fragments=slot_fragments,
        )


class GetUser(runtime.GQLOperation):
    # See: main.py:39
    async def execute(self, *, id: builtins.str) -> GetUserResult:
        return await API_CLIENT.query(
            GetUserResult,
            'query GetUser($id: ID!) {\n  user(id: $id) {\n    ...UserFields\n    posts {\n      id\n      title\n    }\n  }\n}\n\nfragment UserFields on User {\n  id\n  name\n  email\n  phone\n  role\n}',
            variables={"id": id},
            headers=self.headers,
        )


class CreateUser(runtime.GQLOperation):
    # See: main.py:60
    async def execute(self, *, input: CreateUserInput) -> CreateUserResult:
        return await API_CLIENT.query(
            CreateUserResult,
            'mutation CreateUser($input: CreateUserInput!) {\n  createUser(input: $input) {\n    id\n    name\n    email\n    role\n  }\n}',
            variables={"input": input},
            headers=self.headers,
        )


class Search(runtime.GQLOperation):
    # See: main.py:74
    async def execute(self, *, query: str) -> SearchResult:
        return await API_CLIENT.query(
            SearchResult,
            'query Search($query: String!) {\n  search(query: $query) {\n    __typename\n    ... on User {\n      id\n      name\n      role\n    }\n    ... on Post {\n      id\n      title\n      author {\n        name\n      }\n    }\n  }\n}',
            variables={"query": query},
            headers=self.headers,
        )


class GetProfile(runtime.GQLOperation):
    # See: main.py:98
    async def execute(self, *, id: builtins.str, with_email: bool, skip_phone: bool) -> GetProfileResult:
        return await API_CLIENT.query(
            GetProfileResult,
            'query GetProfile($id: ID!, $withEmail: Boolean!, $skipPhone: Boolean!) {\n  user(id: $id) {\n    id\n    name\n    email @include(if: $withEmail)\n    phone @skip(if: $skipPhone)\n    role\n  }\n}',
            variables={"id": id, "withEmail": with_email, "skipPhone": skip_phone},
            headers=self.headers,
        )


class FindUser(runtime.GQLOperation):
    # See: main.py:116, main.py:128
    async def execute(self, *, by: FindUserBy) -> FindUserResult:
        return await API_CLIENT.query(
            FindUserResult,
            'query FindUser($by: FindUserBy!) {\n  findUser(by: $by) {\n    id\n    name\n    email\n  }\n}',
            variables={"by": by},
            headers=self.headers,
        )


class PostAdded(runtime.GQLOperation):
    # See: main.py:144
    def execute(self, *, user_id: builtins.str) -> AbstractAsyncContextManager[AsyncGenerator[PostAddedResult]]:
        return API_CLIENT.subscribe(
            PostAddedResult,
            'subscription PostAdded($userId: ID!) {\n  postAdded(userId: $userId) {\n    id\n    title\n    body\n    author {\n      name\n    }\n  }\n}',
            variables={"userId": user_id},
            headers=self.headers,
        )


class ImageUrl(AttachmentFragment[ImageUrlData]):
    def __init__(self) -> None:
        super().__init__(
            fragment_name='ImageUrl',
            fragment_def='fragment ImageUrl on ImageAttachment {\n  url\n}',
            covered_typenames=frozenset({'ImageAttachment'}),
            adapter=pydantic.TypeAdapter(ImageUrlData),
        )


IMAGE_URL = ImageUrl()


@overload
def api_gql(stmt: Literal['\n        query GetPostAttachment($id: ID!) {\n            post(id: $id) {\n                id\n                attachment @slot { __typename }\n            }\n        }\n    ']) -> GetPostAttachment: ...
@overload
def api_gql(stmt: Literal['\n        query GetUser($id: ID!) {\n            user(id: $id) {\n                ...UserFields\n                posts { id title }\n            }\n        }\n\n        fragment UserFields on User {\n            id\n            name\n            email\n            phone\n            role\n        }\n    ']) -> GetUser: ...
@overload
def api_gql(stmt: Literal['\n        mutation CreateUser($input: CreateUserInput!) {\n            createUser(input: $input) {\n                id\n                name\n                email\n                role\n            }\n        }\n    ']) -> CreateUser: ...
@overload
def api_gql(stmt: Literal['\n        query Search($query: String!) {\n            search(query: $query) {\n                __typename\n                ... on User {\n                    id\n                    name\n                    role\n                }\n                ... on Post {\n                    id\n                    title\n                    author { name }\n                }\n            }\n        }\n    ']) -> Search: ...
@overload
def api_gql(stmt: Literal['\n        query GetProfile($id: ID!, $withEmail: Boolean!, $skipPhone: Boolean!) {\n            user(id: $id) {\n                id\n                name\n                email @include(if: $withEmail)\n                phone @skip(if: $skipPhone)\n                role\n            }\n        }\n    ']) -> GetProfile: ...
@overload
def api_gql(stmt: Literal['\n        query FindUser($by: FindUserBy!) {\n            findUser(by: $by) {\n                id\n                name\n                email\n            }\n        }\n    ']) -> FindUser: ...
@overload
def api_gql(stmt: Literal['\n        subscription PostAdded($userId: ID!) {\n            postAdded(userId: $userId) {\n                id\n                title\n                body\n                author { name }\n            }\n        }\n    ']) -> PostAdded: ...
@overload
def api_gql(stmt: Literal['\n    fragment ImageUrl on ImageAttachment {\n        url\n    }\n']) -> ImageUrl: ...
@overload
def api_gql(stmt: str) -> runtime.GQLOperation | slots.GQLFragment[pydantic.BaseModel]: ...


_API_GQL_DISPATCH: dict[str, type[runtime.GQLOperation]] = {
    '\n        query GetPostAttachment($id: ID!) {\n            post(id: $id) {\n                id\n                attachment @slot { __typename }\n            }\n        }\n    ': GetPostAttachment,
    '\n        query GetUser($id: ID!) {\n            user(id: $id) {\n                ...UserFields\n                posts { id title }\n            }\n        }\n\n        fragment UserFields on User {\n            id\n            name\n            email\n            phone\n            role\n        }\n    ': GetUser,
    '\n        mutation CreateUser($input: CreateUserInput!) {\n            createUser(input: $input) {\n                id\n                name\n                email\n                role\n            }\n        }\n    ': CreateUser,
    '\n        query Search($query: String!) {\n            search(query: $query) {\n                __typename\n                ... on User {\n                    id\n                    name\n                    role\n                }\n                ... on Post {\n                    id\n                    title\n                    author { name }\n                }\n            }\n        }\n    ': Search,
    '\n        query GetProfile($id: ID!, $withEmail: Boolean!, $skipPhone: Boolean!) {\n            user(id: $id) {\n                id\n                name\n                email @include(if: $withEmail)\n                phone @skip(if: $skipPhone)\n                role\n            }\n        }\n    ': GetProfile,
    '\n        query FindUser($by: FindUserBy!) {\n            findUser(by: $by) {\n                id\n                name\n                email\n            }\n        }\n    ': FindUser,
    '\n        subscription PostAdded($userId: ID!) {\n            postAdded(userId: $userId) {\n                id\n                title\n                body\n                author { name }\n            }\n        }\n    ': PostAdded,
}


_API_GQL_FRAGMENTS: dict[str, slots.GQLFragment[pydantic.BaseModel]] = {
    '\n    fragment ImageUrl on ImageAttachment {\n        url\n    }\n': IMAGE_URL,
}


def api_gql(stmt: str) -> runtime.GQLOperation | slots.GQLFragment[pydantic.BaseModel]:
    query_cls = _API_GQL_DISPATCH.get(stmt)
    if query_cls is not None:
        return query_cls()
    fragment = _API_GQL_FRAGMENTS.get(stmt)
    if fragment is not None:
        return fragment
    msg = "unknown GraphQL statement passed to api_gql; "
    msg += "the generator only discovers bare-name calls with a "
    msg += "single string literal - check the call site, then "
    msg += "regenerate the package"
    raise LookupError(msg)
