from __future__ import annotations
# Code generated by iron_gql, DO NOT EDIT.
# fmt: off
# pyright: reportUnusedImport=false
# ruff: noqa


import datetime
from collections.abc import AsyncGenerator
from contextlib import AbstractAsyncContextManager
from typing import Annotated
from typing import Literal
from typing import overload

import pydantic

from iron_gql import runtime

import pydantic.alias_generators

import builtins

from example.config import GRAPHQL_URL


API_CLIENT = runtime.GQLClient(
    base_url=GRAPHQL_URL,
)


class GQLModel(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True,
        alias_generator=pydantic.alias_generators.to_camel,
        extra="forbid",
        validate_default=True,
    )


type Role = Literal['ADMIN', 'MEMBER']


class GetUserResultUserPosts(GQLModel):
    id: builtins.str
    title: str


class GetUserResultUser(GQLModel):
    id: builtins.str
    name: str
    email: str
    phone: str
    role: Role
    posts: list[GetUserResultUserPosts]


class GetUserResult(GQLModel):
    user: GetUserResultUser | None


class CreateUserResultCreateUser(GQLModel):
    id: builtins.str
    name: str
    email: str
    role: Role


class CreateUserResult(GQLModel):
    create_user: CreateUserResultCreateUser


class SearchResultSearchPostAuthor(GQLModel):
    name: str


class SearchResultSearchPost(GQLModel):
    typename__: Literal["Post"] = pydantic.Field(alias="__typename")
    id: builtins.str
    title: str
    author: SearchResultSearchPostAuthor


class SearchResultSearchUser(GQLModel):
    typename__: Literal["User"] = pydantic.Field(alias="__typename")
    id: builtins.str
    name: str
    role: Role


type SearchResultSearch = Annotated[SearchResultSearchPost | SearchResultSearchUser, pydantic.Field(discriminator="typename__")]


class SearchResult(GQLModel):
    search: list[SearchResultSearch]


class GetProfileResultUser(GQLModel):
    id: builtins.str
    name: str
    role: Role
    email: str | None = None
    phone: str | None = None


class GetProfileResult(GQLModel):
    user: GetProfileResultUser | None


class FindUserResultFindUser(GQLModel):
    id: builtins.str
    name: str
    email: str


class FindUserResult(GQLModel):
    find_user: FindUserResultFindUser | None


class PostAddedResultPostAddedAuthor(GQLModel):
    name: str


class PostAddedResultPostAdded(GQLModel):
    id: builtins.str
    title: str
    body: str
    author: PostAddedResultPostAddedAuthor


class PostAddedResult(GQLModel):
    post_added: PostAddedResultPostAdded


class CreateUserInput(GQLModel):
    name: str
    email: str
    role: Role


class FindUserById(GQLModel):
    id: builtins.str


class FindUserByEmail(GQLModel):
    email: str


type FindUserBy = FindUserById | FindUserByEmail


class GetUser(runtime.GQLOperation):
    # See: example/main.py:12
    async def execute(self, *, id: builtins.str) -> GetUserResult:
        return await API_CLIENT.query(
            GetUserResult,
            'query GetUser($id: ID!) {\n  user(id: $id) {\n    ...UserFields\n    posts {\n      id\n      title\n    }\n  }\n}\n\nfragment UserFields on User {\n  id\n  name\n  email\n  phone\n  role\n}',
            variables={"id": id},
            headers=self.headers,
        )


class CreateUser(runtime.GQLOperation):
    # See: example/main.py:33
    async def execute(self, *, input: CreateUserInput) -> CreateUserResult:
        return await API_CLIENT.query(
            CreateUserResult,
            'mutation CreateUser($input: CreateUserInput!) {\n  createUser(input: $input) {\n    id\n    name\n    email\n    role\n  }\n}',
            variables={"input": input},
            headers=self.headers,
        )


class Search(runtime.GQLOperation):
    # See: example/main.py:47
    async def execute(self, *, query: str) -> SearchResult:
        return await API_CLIENT.query(
            SearchResult,
            'query Search($query: String!) {\n  search(query: $query) {\n    __typename\n    ... on User {\n      id\n      name\n      role\n    }\n    ... on Post {\n      id\n      title\n      author {\n        name\n      }\n    }\n  }\n}',
            variables={"query": query},
            headers=self.headers,
        )


class GetProfile(runtime.GQLOperation):
    # See: example/main.py:71
    async def execute(self, *, id: builtins.str, with_email: bool, skip_phone: bool) -> GetProfileResult:
        return await API_CLIENT.query(
            GetProfileResult,
            'query GetProfile($id: ID!, $withEmail: Boolean!, $skipPhone: Boolean!) {\n  user(id: $id) {\n    id\n    name\n    email @include(if: $withEmail)\n    phone @skip(if: $skipPhone)\n    role\n  }\n}',
            variables={"id": id, "withEmail": with_email, "skipPhone": skip_phone},
            headers=self.headers,
        )


class FindUser(runtime.GQLOperation):
    # See: example/main.py:89, example/main.py:101
    async def execute(self, *, by: FindUserBy) -> FindUserResult:
        return await API_CLIENT.query(
            FindUserResult,
            'query FindUser($by: FindUserBy!) {\n  findUser(by: $by) {\n    id\n    name\n    email\n  }\n}',
            variables={"by": by},
            headers=self.headers,
        )


class PostAdded(runtime.GQLOperation):
    # See: example/main.py:113
    def execute(self, *, user_id: builtins.str) -> AbstractAsyncContextManager[AsyncGenerator[PostAddedResult]]:
        return API_CLIENT.subscribe(
            PostAddedResult,
            'subscription PostAdded($userId: ID!) {\n  postAdded(userId: $userId) {\n    id\n    title\n    body\n    author {\n      name\n    }\n  }\n}',
            variables={"userId": user_id},
            headers=self.headers,
        )


@overload
def api_gql(stmt: Literal['\n        query GetUser($id: ID!) {\n            user(id: $id) {\n                ...UserFields\n                posts { id title }\n            }\n        }\n\n        fragment UserFields on User {\n            id\n            name\n            email\n            phone\n            role\n        }\n    ']) -> GetUser: ...
@overload
def api_gql(stmt: Literal['\n        mutation CreateUser($input: CreateUserInput!) {\n            createUser(input: $input) {\n                id\n                name\n                email\n                role\n            }\n        }\n    ']) -> CreateUser: ...
@overload
def api_gql(stmt: Literal['\n        query Search($query: String!) {\n            search(query: $query) {\n                __typename\n                ... on User {\n                    id\n                    name\n                    role\n                }\n                ... on Post {\n                    id\n                    title\n                    author { name }\n                }\n            }\n        }\n    ']) -> Search: ...
@overload
def api_gql(stmt: Literal['\n        query GetProfile($id: ID!, $withEmail: Boolean!, $skipPhone: Boolean!) {\n            user(id: $id) {\n                id\n                name\n                email @include(if: $withEmail)\n                phone @skip(if: $skipPhone)\n                role\n            }\n        }\n    ']) -> GetProfile: ...
@overload
def api_gql(stmt: Literal['\n        query FindUser($by: FindUserBy!) {\n            findUser(by: $by) {\n                id\n                name\n                email\n            }\n        }\n    ']) -> FindUser: ...
@overload
def api_gql(stmt: Literal['\n        subscription PostAdded($userId: ID!) {\n            postAdded(userId: $userId) {\n                id\n                title\n                body\n                author { name }\n            }\n        }\n    ']) -> PostAdded: ...
@overload
def api_gql(stmt: str) -> runtime.GQLOperation: ...


_API_GQL_DISPATCH: dict[str, type[runtime.GQLOperation]] = {
    '\n        query GetUser($id: ID!) {\n            user(id: $id) {\n                ...UserFields\n                posts { id title }\n            }\n        }\n\n        fragment UserFields on User {\n            id\n            name\n            email\n            phone\n            role\n        }\n    ': GetUser,
    '\n        mutation CreateUser($input: CreateUserInput!) {\n            createUser(input: $input) {\n                id\n                name\n                email\n                role\n            }\n        }\n    ': CreateUser,
    '\n        query Search($query: String!) {\n            search(query: $query) {\n                __typename\n                ... on User {\n                    id\n                    name\n                    role\n                }\n                ... on Post {\n                    id\n                    title\n                    author { name }\n                }\n            }\n        }\n    ': Search,
    '\n        query GetProfile($id: ID!, $withEmail: Boolean!, $skipPhone: Boolean!) {\n            user(id: $id) {\n                id\n                name\n                email @include(if: $withEmail)\n                phone @skip(if: $skipPhone)\n                role\n            }\n        }\n    ': GetProfile,
    '\n        query FindUser($by: FindUserBy!) {\n            findUser(by: $by) {\n                id\n                name\n                email\n            }\n        }\n    ': FindUser,
    '\n        subscription PostAdded($userId: ID!) {\n            postAdded(userId: $userId) {\n                id\n                title\n                body\n                author { name }\n            }\n        }\n    ': PostAdded,
}


def api_gql(stmt: str) -> runtime.GQLOperation:
    query_cls = _API_GQL_DISPATCH.get(stmt)
    if query_cls is not None:
        return query_cls()
    return runtime.GQLOperation()
