from __future__ import annotations
# Code generated by iron_gql, DO NOT EDIT.
# fmt: off
# pyright: reportUnusedImport=false, reportUnsafeMultipleInheritance=false
# ruff: noqa


import datetime
from collections.abc import Generator
from collections.abc import Sequence
from contextlib import AbstractContextManager
from typing import Annotated
from typing import Any
from typing import ClassVar
from typing import Literal
from typing import Never
from typing import Self
from typing import overload
from typing import override

import pydantic

from iron_gql import runtime
from iron_gql import slots

import pydantic.alias_generators

import builtins

from example.config import GRAPHQL_URL


API_SYNC_CLIENT = runtime.GQLClient(
    base_url=GRAPHQL_URL,
)


class GQLModel(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True,
        serialize_by_alias=True,
        alias_generator=pydantic.AliasGenerator(
            validation_alias=pydantic.alias_generators.to_camel,
            serialization_alias=pydantic.alias_generators.to_camel,
        ),
        extra="forbid",
        validate_default=True,
    )

    # A template's result model is subscripted with its slots' offered
    # fragments (e.g. `GetAttachmentResult[ImageParts | NodeId]`), which
    # builds and caches a genuine subclass rather than reusing the base -- the
    # override below keeps that subclass's name, and so every ValidationError
    # title raised through it, on the plain model name.
    @classmethod
    @override
    def model_parametrized_name(cls, params: tuple[type[Any], ...]) -> str:
        return cls.__name__


class GQLOpenModel(GQLModel):
    model_config = pydantic.ConfigDict(extra="ignore")


class GQLSlotModel[TOffered](GQLOpenModel, slots.GQLSlotNode[TOffered]):
    pass


type Role = Literal['ADMIN', 'MEMBER']


class UserWithEmailIdNameRole(GQLModel):
    id: builtins.str
    name: str
    email: str
    role: Role


class GetUserResult(GQLModel):
    user: UserWithEmailIdNameRole | None


class CreateUserResult(GQLModel):
    create_user: UserWithEmailIdNameRole


class UserWithName(GQLModel):
    name: str


class PostWithAuthorBodyIdTitle(GQLModel):
    id: builtins.str
    title: str
    body: str
    author: UserWithName


class PostAddedResult(GQLModel):
    post_added: PostWithAuthorBodyIdTitle


class GetPostAttachmentResultPostAttachmentSlotImageAttachment[TAttachment](GQLSlotModel[TAttachment]):
    slot_name__: ClassVar[str] = "attachment"
    typename__: Annotated[Literal["ImageAttachment"], pydantic.Field(validation_alias="__typename", serialization_alias="__typename")]


class GetPostAttachmentResultPostAttachmentSlotLinkAttachment[TAttachment](GQLSlotModel[TAttachment]):
    slot_name__: ClassVar[str] = "attachment"
    typename__: Annotated[Literal["LinkAttachment"], pydantic.Field(validation_alias="__typename", serialization_alias="__typename")]


type GetPostAttachmentResultPostAttachmentSlot[TAttachment] = Annotated[GetPostAttachmentResultPostAttachmentSlotImageAttachment[TAttachment] | GetPostAttachmentResultPostAttachmentSlotLinkAttachment[TAttachment], pydantic.Field(discriminator="typename__")]


class PostWithAttachmentId[TAttachment](GQLModel):
    id: builtins.str
    attachment: GetPostAttachmentResultPostAttachmentSlot[TAttachment] | None


class GetPostAttachmentResult[TAttachment](GQLModel):
    post: PostWithAttachmentId[TAttachment] | None


class ImageUrlData(GQLOpenModel):
    url: str


class LinkUrlData(GQLOpenModel):
    href: str


class CreateUserInput(GQLModel):
    name: str
    email: str
    role: Role


class GetUser(runtime.GQLOperation):
    # See: main_sync.py:6
    def execute(self, *, id: builtins.str) -> GetUserResult:
        return API_SYNC_CLIENT.query(
            GetUserResult,
            'query GetUser($id: ID!) {\n  user(id: $id) {\n    id\n    name\n    email\n    role\n  }\n}',
            variables={"id": id},
            headers=self.headers,
        )


class CreateUser(runtime.GQLOperation):
    # See: main_sync.py:20
    def execute(self, *, input: CreateUserInput) -> CreateUserResult:
        return API_SYNC_CLIENT.query(
            CreateUserResult,
            'mutation CreateUser($input: CreateUserInput!) {\n  createUser(input: $input) {\n    id\n    name\n    email\n    role\n  }\n}',
            variables={"input": input},
            headers=self.headers,
        )


class PostAdded(runtime.GQLOperation):
    # See: main_sync.py:70
    def execute(self, *, user_id: builtins.str) -> AbstractContextManager[Generator[PostAddedResult]]:
        return API_SYNC_CLIENT.subscribe(
            PostAddedResult,
            'subscription PostAdded($userId: ID!) {\n  postAdded(userId: $userId) {\n    id\n    title\n    body\n    author {\n      name\n    }\n  }\n}',
            variables={"userId": user_id},
            headers=self.headers,
        )


class ImageUrl(slots.GQLFragment[ImageUrlData]):
    pass


IMAGE_URL = ImageUrl(
    fragment_name='ImageUrl',
    adapter=pydantic.TypeAdapter(ImageUrlData),
)


class LinkUrl(slots.GQLFragment[LinkUrlData]):
    pass


LINK_URL = LinkUrl(
    fragment_name='LinkUrl',
    adapter=pydantic.TypeAdapter(LinkUrlData),
)


class GetPostAttachmentBound[TAttachment](runtime.GQLBoundOperation):
    def execute(self, *, id: builtins.str) -> GetPostAttachmentResult[TAttachment]:
        return API_SYNC_CLIENT.query(
            GetPostAttachmentResult[TAttachment],
            self.exec_source__,
            variables={"id": id, **self.fragment_args__()},
            headers=self.headers,
            slot_handles=self.slot_handles__,
        )


class GetPostAttachmentWithAttachmentImageUrl(GetPostAttachmentBound[ImageUrl]):
    # See: main_sync.py:56
    exec_source__ = 'query GetPostAttachment($id: ID!) {\n  post(id: $id) {\n    id\n    attachment {\n      __typename\n      ...ImageUrl\n    }\n  }\n}\n\nfragment ImageUrl on ImageAttachment {\n  url\n}'
    slot_handles__ = {"attachment": (slots.SlotHandle(IMAGE_URL, frozenset({'ImageAttachment'})),)}


class GetPostAttachmentWithAttachmentLinkUrl(GetPostAttachmentBound[LinkUrl]):
    # See: main_sync.py:63
    exec_source__ = 'query GetPostAttachment($id: ID!) {\n  post(id: $id) {\n    id\n    attachment {\n      __typename\n      ...LinkUrl\n    }\n  }\n}\n\nfragment LinkUrl on LinkAttachment {\n  href\n}'
    slot_handles__ = {"attachment": (slots.SlotHandle(LINK_URL, frozenset({'LinkAttachment'})),)}


class GetPostAttachment(runtime.GQLTemplate):
    @overload
    def bind(self, *, attachment: ImageUrl | Sequence[ImageUrl]) -> GetPostAttachmentWithAttachmentImageUrl: ...
    @overload
    def bind(self, *, attachment: LinkUrl | Sequence[LinkUrl]) -> GetPostAttachmentWithAttachmentLinkUrl: ...
    def bind(
        self,
        **fragments: slots.GQLFragment[pydantic.BaseModel] | Sequence[slots.GQLFragment[pydantic.BaseModel]],
    ) -> runtime.GQLBoundOperation:
        cls = _API_SYNC_GQL_BIND_DISPATCH.get(slots.bind_key('GetPostAttachment', fragments))
        if cls is None:
            raise LookupError("unknown bind combination for GetPostAttachment; every fragment a bind passes must be a discovered statement - check the call site, then regenerate the package")
        return cls()


_API_SYNC_GQL_BIND_DISPATCH: dict[slots.BindKey, type[runtime.GQLBoundOperation]] = {
    ('GetPostAttachment', (('attachment', ('ImageUrl',)),)): GetPostAttachmentWithAttachmentImageUrl,
    ('GetPostAttachment', (('attachment', ('LinkUrl',)),)): GetPostAttachmentWithAttachmentLinkUrl,
}


@overload
def api_sync_gql(stmt: Literal['\n        query GetUser($id: ID!) {\n            user(id: $id) {\n                id\n                name\n                email\n                role\n            }\n        }\n    ']) -> GetUser: ...
@overload
def api_sync_gql(stmt: Literal['\n        mutation CreateUser($input: CreateUserInput!) {\n            createUser(input: $input) {\n                id\n                name\n                email\n                role\n            }\n        }\n    ']) -> CreateUser: ...
@overload
def api_sync_gql(stmt: Literal['\n        subscription PostAdded($userId: ID!) {\n            postAdded(userId: $userId) {\n                id\n                title\n                body\n                author { name }\n            }\n        }\n    ']) -> PostAdded: ...
@overload
def api_sync_gql(stmt: Literal['\n        fragment ImageUrl on ImageAttachment {\n            url\n        }\n    ']) -> ImageUrl: ...
@overload
def api_sync_gql(stmt: Literal['\n        fragment LinkUrl on LinkAttachment {\n            href\n        }\n    ']) -> LinkUrl: ...
@overload
def api_sync_gql(stmt: Literal['\n        query GetPostAttachment($id: ID!) {\n            post(id: $id) {\n                id\n                attachment @slot { __typename }\n            }\n        }\n    ']) -> GetPostAttachment: ...
@overload
def api_sync_gql(stmt: str) -> runtime.GQLOperation | slots.GQLFragment[pydantic.BaseModel] | runtime.GQLTemplate: ...


_API_SYNC_GQL_DISPATCH: dict[str, type[runtime.GQLOperation]] = {
    '\n        query GetUser($id: ID!) {\n            user(id: $id) {\n                id\n                name\n                email\n                role\n            }\n        }\n    ': GetUser,
    '\n        mutation CreateUser($input: CreateUserInput!) {\n            createUser(input: $input) {\n                id\n                name\n                email\n                role\n            }\n        }\n    ': CreateUser,
    '\n        subscription PostAdded($userId: ID!) {\n            postAdded(userId: $userId) {\n                id\n                title\n                body\n                author { name }\n            }\n        }\n    ': PostAdded,
}


_API_SYNC_GQL_FRAGMENTS: dict[str, slots.GQLFragment[pydantic.BaseModel]] = {
    '\n        fragment ImageUrl on ImageAttachment {\n            url\n        }\n    ': IMAGE_URL,
    '\n        fragment LinkUrl on LinkAttachment {\n            href\n        }\n    ': LINK_URL,
}


_API_SYNC_GQL_TEMPLATES: dict[str, type[runtime.GQLTemplate]] = {
    '\n        query GetPostAttachment($id: ID!) {\n            post(id: $id) {\n                id\n                attachment @slot { __typename }\n            }\n        }\n    ': GetPostAttachment,
}


def api_sync_gql(stmt: str) -> runtime.GQLOperation | slots.GQLFragment[pydantic.BaseModel] | runtime.GQLTemplate:
    query_cls = _API_SYNC_GQL_DISPATCH.get(stmt)
    if query_cls is not None:
        return query_cls()
    fragment = _API_SYNC_GQL_FRAGMENTS.get(stmt)
    if fragment is not None:
        return fragment
    template_cls = _API_SYNC_GQL_TEMPLATES.get(stmt)
    if template_cls is not None:
        return template_cls()
    msg = "unknown GraphQL statement passed to api_sync_gql; "
    msg += "the generator only discovers bare-name calls with a "
    msg += "single string literal - check the call site, then "
    msg += "regenerate the package"
    raise LookupError(msg)
