from __future__ import annotations
# Code generated by iron_gql, DO NOT EDIT.
# fmt: off
# pyright: reportUnusedImport=false
# ruff: noqa


import datetime
from abc import ABC
from abc import abstractmethod
from collections.abc import Generator
from collections.abc import Callable
from collections.abc import Sequence
from contextlib import AbstractContextManager
from typing import Annotated
from typing import Any
from typing import ClassVar
from typing import Literal
from typing import Never
from typing import TypeVar
from typing import cast
from typing import final
from typing import overload
from typing import override

import pydantic

from iron_gql import runtime
from iron_gql import slots

import pydantic.alias_generators

import builtins

from example.config import GRAPHQL_URL


API_SYNC_CLIENT = runtime.GQLClient(
    base_url=GRAPHQL_URL,
)

_API_SYNC_GQL_CAST = cast


class GQLModel(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True,
        serialize_by_alias=True,
        alias_generator=pydantic.AliasGenerator(
            validation_alias=pydantic.alias_generators.to_camel,
            serialization_alias=pydantic.alias_generators.to_camel,
        ),
        extra="forbid",
        validate_default=True,
    )


type Role = Literal['ADMIN', 'MEMBER']


class UserWithEmailIdNameRole(GQLModel):
    id: builtins.str
    name: str
    email: str
    role: Role


class GetUserResult(GQLModel):
    user: UserWithEmailIdNameRole | None


class CreateUserResult(GQLModel):
    create_user: UserWithEmailIdNameRole


class UserWithName(GQLModel):
    name: str


class Post(GQLModel):
    id: builtins.str
    title: str
    body: str
    author: UserWithName


class PostAddedResult(GQLModel):
    post_added: Post


class CreateUserInput(GQLModel):
    name: str
    email: str
    role: Role


class GetUser(runtime.GQLOperation):
    # See: ch08_sync.py:6
    def execute(self, *, id: builtins.str) -> GetUserResult:
        return API_SYNC_CLIENT.query(
            GetUserResult,
            'query GetUser($id: ID!) {\n  user(id: $id) {\n    id\n    name\n    email\n    role\n  }\n}',
            variables={"id": id},
            headers=self.headers,
        )


class CreateUser(runtime.GQLOperation):
    # See: ch08_sync.py:22
    def execute(self, *, input: CreateUserInput) -> CreateUserResult:
        return API_SYNC_CLIENT.query(
            CreateUserResult,
            'mutation CreateUser($input: CreateUserInput!) {\n  createUser(input: $input) {\n    id\n    name\n    email\n    role\n  }\n}',
            variables={"input": input},
            headers=self.headers,
        )


class PostAdded(runtime.GQLOperation):
    # See: ch08_sync.py:38
    def execute(self, *, user_id: builtins.str) -> AbstractContextManager[Generator[PostAddedResult]]:
        return API_SYNC_CLIENT.subscribe(
            PostAddedResult,
            'subscription PostAdded($userId: ID!) {\n  postAdded(userId: $userId) {\n    id\n    title\n    body\n    author {\n      name\n    }\n  }\n}',
            variables={"userId": user_id},
            headers=self.headers,
        )


@overload
def api_sync_gql(stmt: Literal['\n        query GetUser($id: ID!) {\n            user(id: $id) {\n                id\n                name\n                email\n                role\n            }\n        }\n    ']) -> GetUser: ...
@overload
def api_sync_gql(stmt: Literal['\n        mutation CreateUser($input: CreateUserInput!) {\n            createUser(input: $input) {\n                id\n                name\n                email\n                role\n            }\n        }\n    ']) -> CreateUser: ...
@overload
def api_sync_gql(stmt: Literal['\n        subscription PostAdded($userId: ID!) {\n            postAdded(userId: $userId) {\n                id\n                title\n                body\n                author { name }\n            }\n        }\n    ']) -> PostAdded: ...
@overload
def api_sync_gql(stmt: str) -> runtime.GQLOperation: ...


_API_SYNC_GQL_DISPATCH: dict[str, type[runtime.GQLOperation]] = {
    '\n        query GetUser($id: ID!) {\n            user(id: $id) {\n                id\n                name\n                email\n                role\n            }\n        }\n    ': GetUser,
    '\n        mutation CreateUser($input: CreateUserInput!) {\n            createUser(input: $input) {\n                id\n                name\n                email\n                role\n            }\n        }\n    ': CreateUser,
    '\n        subscription PostAdded($userId: ID!) {\n            postAdded(userId: $userId) {\n                id\n                title\n                body\n                author { name }\n            }\n        }\n    ': PostAdded,
}


def api_sync_gql(stmt: str) -> runtime.GQLOperation:
    query_cls = _API_SYNC_GQL_DISPATCH.get(stmt)
    if query_cls is not None:
        return query_cls()
    msg = "unknown GraphQL statement passed to api_sync_gql; "
    msg += "the generator only discovers bare-name calls with a "
    msg += "single string literal - check the call site, then "
    msg += "regenerate the package"
    raise LookupError(msg)
