import keyword
from collections import defaultdict

import pydantic

from iron_gql.codegen.ir import CollectedArtifact
from iron_gql.codegen.ir import CollectedEnum
from iron_gql.codegen.ir import CollectedModel


def validate_collected_names(
    *,
    result_artifacts: list[CollectedArtifact],
    input_artifacts: list[CollectedArtifact],
    enums: list[CollectedEnum],
) -> list[str]:
    # Everything downstream — the rename map and the module namespace — is
    # keyed by these names, so ambiguity or an unusable identifier must be
    # rejected here, before any name-keyed structure is built from them.
    # Raw-name twins in particular would otherwise poison a different consumer
    # each time they slip through.
    return [
        *_twin_errors(result_artifacts),
        *_enum_collision_errors(enums, result_artifacts),
        *_field_name_errors([*result_artifacts, *input_artifacts]),
    ]


def _twin_errors(result_artifacts: list[CollectedArtifact]) -> list[str]:
    groups: dict[str, list[CollectedArtifact]] = defaultdict(list)
    for artifact in result_artifacts:
        groups[artifact.name].append(artifact)
    return [
        error
        for name, group in groups.items()
        if len(group) > 1 and (error := _twin_error(name, group)) is not None
    ]


def _twin_error(name: str, group: list[CollectedArtifact]) -> str | None:
    models = [artifact for artifact in group if isinstance(artifact, CollectedModel)]
    if len(models) != len(group):
        return (
            f"Name '{name}' is generated by two colliding selections; alias "
            "one of the fields"
        )
    shapes = {model.shape_key for model in models}
    if len(shapes) == 1:
        # Identical twins merge into a single model downstream.
        return None
    return (
        f"Model name '{name}' is generated by colliding field paths with "
        "different shapes; alias one of the fields to give the models "
        "distinct names"
    )


def _enum_collision_errors(
    enums: list[CollectedEnum],
    result_artifacts: list[CollectedArtifact],
) -> list[str]:
    # A NamedRef carries only a name, so an enum sharing one with a generated
    # model is ambiguous everywhere a ref is resolved.
    artifact_names = {artifact.name for artifact in result_artifacts}
    return [
        _enum_collision_error(enum) for enum in enums if enum.name in artifact_names
    ]


def _enum_collision_error(enum: CollectedEnum) -> str:
    return (
        f"Enum '{enum.name}' shares its name with a generated model; rename "
        "the enum or alias the colliding field"
    )


def _field_name_errors(artifacts: list[CollectedArtifact]) -> list[str]:
    errors: list[str] = []
    for artifact in artifacts:
        if isinstance(artifact, CollectedModel):
            errors.extend(_model_field_errors(artifact))
    return errors


def _model_field_errors(model: CollectedModel) -> list[str]:
    errors: list[str] = []
    # Two response keys snaking to one Python name would render the same
    # attribute twice; the second silently wins at class creation.
    by_python_name: dict[str, str] = {}
    for field in model.fields:
        previous = by_python_name.setdefault(field.name, field.response_key)
        if previous != field.response_key:
            msg = (
                f"Fields '{previous}' and '{field.response_key}' of model "
                f"'{model.name}' both map to Python name "
                f"'{field.name}'; alias one of them"
            )
            errors.append(msg)
    for field in model.fields:
        if keyword.iskeyword(field.name):
            msg = (
                f"Field '{field.name}' of model '{model.name}' is a "
                "Python keyword; choose a different alias or schema name"
            )
            errors.append(msg)
        if field.name.startswith("model_") and hasattr(pydantic.BaseModel, field.name):
            msg = (
                f"Field '{field.name}' of model '{model.name}' collides "
                "with pydantic.BaseModel's protected namespace; choose a "
                "different alias"
            )
            errors.append(msg)
    return errors
