import keyword
from collections import defaultdict

import pydantic

from iron_gql.codegen.ir import CollectedArtifact
from iron_gql.codegen.ir import CollectedEnum
from iron_gql.codegen.ir import CollectedFragment
from iron_gql.codegen.ir import CollectedModel
from iron_gql.codegen.ir import slot_roots

# The names the slot runtime claims on every GQLSlotNode subclass; a static
# slot selection aliasing one of them would have pydantic turn the metadata
# into a model field and strip the attribute the runtime reads during
# validation. test_slots_runtime.py pins this tuple to the real class's own
# contract names by set equality, so neither side can drift silently.
SLOT_RUNTIME_FIELD_NAMES = (
    "slot_name__",
    "_slot_data",
    "slot_data__",
    "add_slot_data__",
    "validate_slot__",
)


def validate_collected_names(
    *,
    result_artifacts: list[CollectedArtifact],
    input_artifacts: list[CollectedArtifact],
    fragments: list[CollectedFragment],
    enums: list[CollectedEnum],
) -> list[str]:
    # Everything downstream — the rename map, the subtree walks, the module
    # namespace — is keyed by these names, so ambiguity or an unusable
    # identifier must be rejected here, before any name-keyed structure is
    # built from them. Raw-name twins in particular would otherwise poison a
    # different consumer each time they slip through.
    return [
        *_twin_errors(result_artifacts, fragments),
        *_enum_collision_errors(enums, result_artifacts),
        *_field_name_errors([*result_artifacts, *input_artifacts]),
    ]


def _slot_origin(model: CollectedModel) -> str:
    if model.slot_name is None:
        return "a non-slot selection"
    return f"slot '{model.slot_name}'"


def _twin_errors(
    result_artifacts: list[CollectedArtifact],
    fragments: list[CollectedFragment],
) -> list[str]:
    pinned = {fragment.model_name: fragment for fragment in fragments}
    groups: dict[str, list[CollectedArtifact]] = defaultdict(list)
    for artifact in result_artifacts:
        groups[artifact.name].append(artifact)
    return [
        error
        for name, group in groups.items()
        if len(group) > 1
        and (error := _twin_error(name, group, pinned.get(name))) is not None
    ]


def _twin_error(
    name: str,
    group: list[CollectedArtifact],
    fragment: CollectedFragment | None,
) -> str | None:
    if fragment is not None:
        return (
            f"Fragment '{fragment.fragment_name}' at {fragment.location} pins "
            f"model name '{name}', which a model of another operation or "
            "fragment also generates; rename the fragment or alias the "
            "colliding field"
        )
    models = [artifact for artifact in group if isinstance(artifact, CollectedModel)]
    if len(models) != len(group):
        return (
            f"Name '{name}' is generated by two colliding selections; alias "
            "one of the fields"
        )
    shapes = {model.shape_key for model in models}
    slot_names = {model.slot_name for model in models}
    if len(shapes) == 1 and len(slot_names) == 1:
        # Identical twins merge into a single model downstream.
        return None
    if len(slot_names) > 1:
        first = models[0]
        second = next(model for model in models if model.slot_name != first.slot_name)
        return (
            f"Model name '{name}' is generated by {_slot_origin(first)} and by "
            f"{_slot_origin(second)}; alias one of the fields to give the "
            "models distinct names"
        )
    slot_name = next(iter(slot_names))
    if slot_name is not None:
        return (
            f"Slot '{slot_name}' generates model '{name}' from two different "
            "selections; alias one of the fields to give the models distinct "
            "names"
        )
    return (
        f"Model name '{name}' is generated by colliding field paths with "
        "different shapes; alias one of the fields to give the models "
        "distinct names"
    )


def _enum_collision_errors(
    enums: list[CollectedEnum],
    result_artifacts: list[CollectedArtifact],
) -> list[str]:
    # A NamedRef carries only a name, so an enum sharing one with a generated
    # model is ambiguous everywhere a ref is resolved — the subtree walks
    # would recurse through the model where the enum was meant.
    artifact_names = {artifact.name for artifact in result_artifacts}
    return [
        _enum_collision_error(enum) for enum in enums if enum.name in artifact_names
    ]


def _enum_collision_error(enum: CollectedEnum) -> str:
    return (
        f"Enum '{enum.name}' shares its name with a generated model; rename "
        "the enum or alias the colliding field"
    )


def _field_name_errors(artifacts: list[CollectedArtifact]) -> list[str]:
    errors: list[str] = []
    for artifact in artifacts:
        if isinstance(artifact, CollectedModel):
            errors.extend(_model_field_errors(artifact))
    for model, _ in slot_roots(artifacts):
        for field in model.fields:
            if field.name in SLOT_RUNTIME_FIELD_NAMES:
                msg = (
                    f"Field '{field.name}' of model '{model.name}' collides "
                    "with the slot runtime contract; choose a different alias"
                )
                errors.append(msg)
    return errors


def _model_field_errors(model: CollectedModel) -> list[str]:
    errors: list[str] = []
    # Two response keys snaking to one Python name would render the same
    # attribute twice; the second silently wins at class creation.
    by_python_name: dict[str, str] = {}
    for field in model.fields:
        previous = by_python_name.setdefault(field.name, field.response_key)
        if previous != field.response_key:
            msg = (
                f"Fields '{previous}' and '{field.response_key}' of model "
                f"'{model.name}' both map to Python name "
                f"'{field.name}'; alias one of them"
            )
            errors.append(msg)
    for field in model.fields:
        if keyword.iskeyword(field.name):
            msg = (
                f"Field '{field.name}' of model '{model.name}' is a "
                "Python keyword; choose a different alias or schema name"
            )
            errors.append(msg)
        if field.name.startswith("model_") and hasattr(pydantic.BaseModel, field.name):
            msg = (
                f"Field '{field.name}' of model '{model.name}' collides "
                "with pydantic.BaseModel's protected namespace; choose a "
                "different alias"
            )
            errors.append(msg)
    return errors
