from dataclasses import dataclass
from typing import Literal

from iron_gql.codegen.ir import CollectedArtifact
from iron_gql.codegen.ir import CollectedBinding
from iron_gql.codegen.ir import CollectedBindingArg
from iron_gql.codegen.ir import CollectedBindingSlot
from iron_gql.codegen.ir import CollectedEnum
from iron_gql.codegen.ir import CollectedField
from iron_gql.codegen.ir import CollectedFragment
from iron_gql.codegen.ir import CollectedModel
from iron_gql.codegen.ir import CollectedOperation
from iron_gql.codegen.ir import CollectedOperationVar
from iron_gql.codegen.ir import CollectedPackageIR
from iron_gql.codegen.ir import CollectedSlotHandle
from iron_gql.codegen.ir import CollectedTemplate
from iron_gql.codegen.ir import CollectedUnionAlias
from iron_gql.codegen.ir import ImportRef
from iron_gql.codegen.ir import bindings_by_template
from iron_gql.codegen.ir import render_type_expr
from iron_gql.codegen.ir import slot_roots
from iron_gql.codegen.util import indent_block
from iron_gql.naming import client_binding_name
from iron_gql.slots import BindKey
from iron_gql.slots import bind_key_shape


def render_header(*, unsafe_multiple_inheritance: bool) -> str:
    # `reportUnsafeMultipleInheritance` is off only for modules that render
    # the one multi-base class this generator ever produces: the slot model
    # base (`GQLModel` plus the slot node). A fragment handle always derives
    # from a single `slots.GQLFragment[Model]` base, so it never needs this.
    suppressions = "reportUnusedImport=false"
    if unsafe_multiple_inheritance:
        suppressions += ", reportUnsafeMultipleInheritance=false"
    return f"""\
from __future__ import annotations
# Code generated by iron_gql, DO NOT EDIT.
# fmt: off
# pyright: {suppressions}
# ruff: noqa"""


# The module-level names the scaffold binds, kept in one place because
# `scaffold_claims` hands the same set to the collision rule and everything
# below renders from these very names. Each tuple is already sorted: the import
# blocks are emitted in this order.
MODEL_BASE_NAME = "GQLModel"
OPEN_MODEL_BASE_NAME = "GQLOpenModel"
SLOT_MODEL_BASE_NAME = "GQLSlotModel"
BASE_CLASS_NAMES = (MODEL_BASE_NAME, OPEN_MODEL_BASE_NAME, SLOT_MODEL_BASE_NAME)
STDLIB_MODULE_NAMES = ("datetime",)
# Imported unconditionally and referenced by every model, so it is reserved
# unconditionally too — deriving the claim from `to_camel_ref` instead would
# drop it as soon as a package points that option somewhere other than pydantic.
THIRD_PARTY_MODULE_NAMES = ("pydantic",)
# Both modes' names are reserved whichever mode a package is generated in: the
# reserved set must not depend on the mode in force today, or switching a
# package to the other mode would rebind a name that generated fine before.
CONTEXTLIB_NAMES = ("AbstractAsyncContextManager", "AbstractContextManager")
GENERATOR_NAMES = ("AsyncGenerator", "Generator")
ABC_NAMES = (*GENERATOR_NAMES, "Sequence")
# A template's bound base declares `execute` and leaves it to each binding,
# which is what `abc` spells: without it the declaration reads as a method
# ignoring its own parameters.
ABC_MODULE_NAMES = ("ABC", "abstractmethod")
# `Self` is the return type of a binding's `with_args`; an unfilled slot
# spells `Never` twice over -- as its node's phantom (`render_slot_class`) and
# as the element type of its `bind()` parameter (`_bind_param`).
TYPING_NAMES = (
    "Annotated",
    "ClassVar",
    "Literal",
    "Never",
    "Self",
    "overload",
    "override",
)
IRON_GQL_NAMES = ("runtime", "slots")
# The one name in this block the module never binds: it is a PEP 695 parameter
# written *inside* a template's bound base (`render_template_bases`), where it
# shadows a module-level model or enum spelled the same. `execute`'s variable
# annotations are rendered in that scope, so a schema with an `input TResult`
# used as a template variable makes the base read `TResult` as its own
# parameter while every binding's override reads the model -- a package that
# generates cleanly and then fails to type-check. Reserved rather than renamed
# out of the way: every name a parameter could take is a name a schema can
# spell, so only a claim closes the case.
BOUND_RESULT_PARAM = "TResult"


def _module_dict_name(package_name: str, kind: str) -> str:
    # The private module-level dicts the scaffold binds. Spelled once: the
    # renderer writes each of these names and `scaffold_claims` reserves them,
    # and a name reserved under one spelling but rendered under another silently
    # drops it from collision protection.
    return f"_{package_name.upper()}_GQL_{kind}"


# A slot payload carries every passed fragment's fields next to the static
# selection, and a fragment validates that same payload for its own fields —
# so every model validating inside a slot or fragment subtree ignores the
# keys other readers asked for instead of forbidding them. Isolation is not
# lost: a model exposes only the fields its own selection declared.
OPEN_BASE = f"""\
class {OPEN_MODEL_BASE_NAME}({MODEL_BASE_NAME}):
    model_config = pydantic.ConfigDict(extra="ignore")"""

_SLOT_BASES = f"{OPEN_MODEL_BASE_NAME}, slots.GQLSlotNode[TOffered]"
# `TOffered` is a PEP 695 parameter that does nothing but pass through to the
# contravariant phantom of `slots.GQLSlotNode`, which is where its variance
# comes from: a node offering more fragments stays acceptable where fewer are
# expected. Unlike `BOUND_RESULT_PARAM` it claims nothing: this base's body is
# `pass`, so there is no module-level name it could shadow.
SLOT_BASE = f"""\
class {SLOT_MODEL_BASE_NAME}[TOffered]({_SLOT_BASES}):
    pass"""


type GenerationMode = Literal["async", "sync"]


@dataclass(frozen=True, slots=True)
class ModeConfig:
    client_class: str
    async_kw: str
    await_kw: str
    stream_context: str
    generator: str


RENDER_MODES: dict[GenerationMode, ModeConfig] = {
    "async": ModeConfig(
        client_class="AsyncGQLClient",
        async_kw="async ",
        await_kw="await ",
        stream_context="AbstractAsyncContextManager",
        generator="AsyncGenerator",
    ),
    "sync": ModeConfig(
        client_class="GQLClient",
        async_kw="",
        await_kw="",
        stream_context="AbstractContextManager",
        generator="Generator",
    ),
}


def scaffold_claims(
    *,
    package_name: str,
    gql_fn_name: str,
    base_url_ref: ImportRef,
    scalars: dict[str, ImportRef],
    to_camel_ref: ImportRef,
) -> dict[str, tuple[str, ...]]:
    # Names only imported when a package uses slots or fragments are listed
    # unconditionally: the reserved set must not depend on which optional
    # features a package happens to use today, or adding a slot to it would
    # rebind a name that generated fine a commit earlier.
    #
    # Each binding keeps its origin so the collision rule can tell two
    # scaffold sources fighting over one name apart from one binding listed
    # twice: identical origins (the same import statement reached from two
    # configs, e.g. `import pydantic`) collapse into a single claim, while
    # different origins for one name are a real collision.
    pairs: list[tuple[str, str]] = [
        *((name, "the generated model base class") for name in BASE_CLASS_NAMES),
        *((module, f"import {module}") for module in STDLIB_MODULE_NAMES),
        *((module, f"import {module}") for module in THIRD_PARTY_MODULE_NAMES),
        *((name, f"from contextlib import {name}") for name in CONTEXTLIB_NAMES),
        *((name, f"from collections.abc import {name}") for name in ABC_NAMES),
        *((name, f"from abc import {name}") for name in ABC_MODULE_NAMES),
        *((name, f"from typing import {name}") for name in TYPING_NAMES),
        *((name, f"from iron_gql import {name}") for name in IRON_GQL_NAMES),
        (BOUND_RESULT_PARAM, "the type parameter of a template's bound base"),
        (gql_fn_name, "the generated gql function"),
        (client_binding_name(package_name), "the generated client binding"),
        *(
            (_module_dict_name(package_name, kind), description)
            for kind, description in (
                ("DISPATCH", "the generated dispatch dict"),
                ("FRAGMENTS", "the generated fragments dict"),
                ("PASSTHROUGH", "the generated passthrough set"),
                ("TEMPLATES", "the generated templates dict"),
                ("BIND_DISPATCH", "the generated bind dispatch dict"),
            )
        ),
        (base_url_ref.root_symbol, base_url_ref.import_statement()),
        (to_camel_ref.root_module, f"import {to_camel_ref.root_module}"),
        *((ref.root_module, f"import {ref.root_module}") for ref in scalars.values()),
    ]
    claims: dict[str, dict[str, None]] = {}
    for name, origin in pairs:
        claims.setdefault(name, {})[origin] = None
    return {name: tuple(origins) for name, origins in claims.items()}


def render_field(field: CollectedField) -> str:
    rendered_type = render_type_expr(field.rendered_type)
    default_expr = field.default_expr
    if field.is_conditional and default_expr is None:
        default_expr = "None"

    if field.alias is not None:
        rendered_type = (
            f"Annotated[{rendered_type}, "
            f'pydantic.Field(validation_alias="{field.alias}", '
            f'serialization_alias="{field.alias}")]'
        )
    if default_expr is not None:
        return f"{field.name}: {rendered_type} = {default_expr}"
    return f"{field.name}: {rendered_type}"


def render_pydantic_class(model: CollectedModel, base: str) -> str:
    rendered_fields = "\n".join(render_field(field) for field in model.fields)
    header = f"class {model.name}{_type_params(model.type_params)}({base}):"
    return f"{header}\n    {indent_block(rendered_fields, '    ')}"


def render_slot_class(model: CollectedModel) -> str:
    # A node model is the phantom's one destination: the parameter threaded
    # down the path to it lands here, in the slot base, and each binding fills
    # it with the fragment classes readable at this slot.
    if not model.type_params:
        # Internal invariant: a node model is its own slot's model, and
        # `collect.parametrize_slot_paths` seeds the walk with exactly those.
        msg = f"slot node {model.name!r} reached the renderer unparametrised"
        raise AssertionError(msg)
    offered = ", ".join(model.type_params)
    body = "\n".join([
        f'slot_name__: ClassVar[str] = "{model.slot_name}"',
        *(render_field(field) for field in model.fields),
    ])
    header = (
        f"class {model.name}{_type_params(model.type_params)}"
        f"({SLOT_MODEL_BASE_NAME}[{offered}]):"
    )
    return f"{header}\n    {indent_block(body, '    ')}"


def _type_params(type_params: tuple[str, ...]) -> str:
    # PEP 695 parameters, declared on the model itself: their order is the
    # model's own statement, which a parametrised base cannot make when the
    # model reaches two slots. Variance is left to inference and lands where it
    # belongs -- a parameter that only reaches `slots.GQLSlotNode`'s
    # contravariant phantom infers contravariant, one behind a `list[...]`
    # field infers invariant, and invariant is the truth for a mutable field.
    # Shared code that wants any binding's result spells the phantom `Any`,
    # which is assignable both ways whatever the variance came out as.
    #
    # The parameters are visible in pydantic's JSON Schema -- `$defs` keys and
    # titles carry the fragment class names (`Post_ImageParts_`) -- so two
    # bindings of one template describe the same shape under two names. The
    # phantom is not a field and nothing validates by it; a consumer diffing
    # schema snapshots is the one this shows up for.
    if not type_params:
        return ""
    # Each defaults to `Never` (PEP 696), so the bare `{Op}Result` an
    # annotation may still spell means "readable by nothing" rather than an
    # unparametrised generic -- the same bottom `slots.GQLSlotNode` declares
    # for its own phantom.
    defaulted = ", ".join(f"{name} = Never" for name in type_params)
    return f"[{defaulted}]"


def render_imports(
    to_camel_ref: ImportRef,
    scalars: dict[str, ImportRef],
    base_url_ref: ImportRef,
    mode: ModeConfig,
) -> str:
    import_modules = [ref.module for ref in scalars.values()]
    scalar_imports = "\n".join(f"import {module}" for module in import_modules)
    # Every fixed name is emitted whole, whichever features the package
    # happens to use: the module suppresses unused imports, so an extra line
    # costs nothing, while a predicate that drifts from the emitter that
    # writes the name costs a NameError in generated code -- and
    # `scaffold_claims` already reserves the same names unconditionally for
    # exactly that reason. Only the mode-owned pairs are a choice, and
    # `ModeConfig` is what chooses.
    abstract_imports = "\n".join(f"from abc import {name}" for name in ABC_MODULE_NAMES)
    abc_imports = "\n".join(
        f"from collections.abc import {name}"
        for name in ABC_NAMES
        if name not in GENERATOR_NAMES or name == mode.generator
    )
    typing_imports = "\n".join(f"from typing import {name}" for name in TYPING_NAMES)
    iron_gql_imports = "\n".join(
        f"from iron_gql import {name}" for name in IRON_GQL_NAMES
    )
    stdlib_imports = "\n".join(f"import {module}" for module in STDLIB_MODULE_NAMES)
    contextlib_imports = f"from contextlib import {mode.stream_context}"
    third_party_imports = "\n".join(
        f"import {module}" for module in THIRD_PARTY_MODULE_NAMES
    )
    return f"""\
{stdlib_imports}
{abstract_imports}
{abc_imports}
{contextlib_imports}
{typing_imports}

{third_party_imports}

{iron_gql_imports}

import {to_camel_ref.module}

{scalar_imports}

{base_url_ref.import_statement()}"""


def render_client_init(
    package_name: str,
    base_url_ref: ImportRef,
    to_camel_ref: ImportRef,
    mode: ModeConfig,
) -> str:
    return f"""\
{client_binding_name(package_name)} = runtime.{mode.client_class}(
    base_url={base_url_ref.symbol},
)


class {MODEL_BASE_NAME}(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True,
        serialize_by_alias=True,
        alias_generator=pydantic.AliasGenerator(
            validation_alias={to_camel_ref.dotted_path},
            serialization_alias={to_camel_ref.dotted_path},
        ),
        extra="forbid",
        validate_default=True,
    )"""


def render_fragments(fragments: list[CollectedFragment]) -> list[str]:
    # Metadata is passed to the runtime constructor rather than pinned in
    # ClassVars: the adapter parameter is invariant in the handle's model, so
    # a mismatch between the base and the adapter is a static error.
    #
    # A handle derives straight from `slots.GQLFragment[Model]`: a bind
    # dispatches on the fragment name alone, not on any compatibility base.
    #
    # The metadata is supplied at the one call that builds the singleton, and
    # the class adds no constructor of its own -- so `ImageParts()` is a static
    # error at the call site rather than a second handle for one fragment. A
    # handle is an identity token (`GQLSlotNode._slot_data` is keyed by
    # `id(handle)`), and a zero-argument constructor offered a second one that
    # type-checked everywhere the singleton does: `bind()` accepted it, keyed
    # the dispatch by fragment name as always, and the bound operation carried
    # the singleton's handles -- so the fresh instance only failed at `read`,
    # claiming the fragment was not part of a binding it plainly was.
    rendered: list[str] = []
    for fragment in fragments:
        base = f"slots.GQLFragment[{fragment.model_name}]"
        handle_class = f"class {fragment.class_name}({base}):\n    pass"
        singleton = "\n".join([
            f"{fragment.singleton_name} = {fragment.class_name}(",
            f"    fragment_name={fragment.fragment_name!r},",
            f"    adapter=pydantic.TypeAdapter({fragment.model_name}),",
            ")",
        ])
        rendered.append(f"{handle_class}\n\n\n{singleton}")
    return rendered


@dataclass(kw_only=True, frozen=True)
class _LookupTable:
    # One module-level dict `gql()` consults, and the three lines that consult
    # it. Every kind of statement the generated module can hand back differs
    # from the others in exactly these fields.
    dict_name: str
    value_type: str
    # What this kind contributes to the catch-all overload's return union when
    # the package contains one -- see `render_gql_fn`, which folds the
    # non-empty tables' contributions together.
    catch_all_type: str
    # (statement literal, the type this kind's Literal overload returns, the
    # expression the dict maps the literal to). The last two coincide for the
    # kinds whose dict holds the very class the overload names; a fragment's
    # dict holds its shared singleton instead.
    entries: list[tuple[str, str, str]]
    # The name the lookup binds and what it returns. Rendered inside `gql()`,
    # whose only other name is its `stmt` parameter, so these cannot collide
    # with anything a developer wrote.
    local: str
    returned: str

    def render_dict(self) -> str:
        return "\n".join([
            f"{self.dict_name}: dict[str, {self.value_type}] = {{",
            "\n".join(f"    {literal}: {value}," for literal, _, value in self.entries),
            "}",
        ])

    def render_lookup(self) -> list[str]:
        return [
            f"    {self.local} = {self.dict_name}.get(stmt)",
            f"    if {self.local} is not None:",
            f"        return {self.returned}",
        ]


def render_gql_fn(
    operations: list[CollectedOperation],
    fragments: list[CollectedFragment],
    templates: list[CollectedTemplate],
    package_name: str,
    gql_fn_name: str,
    passthrough_texts: tuple[str, ...],
) -> str:
    dict_name = _module_dict_name(package_name, "DISPATCH")
    fragments_dict_name = _module_dict_name(package_name, "FRAGMENTS")
    templates_dict_name = _module_dict_name(package_name, "TEMPLATES")
    passthrough_name = _module_dict_name(package_name, "PASSTHROUGH")
    handle_type = "slots.GQLFragment[pydantic.BaseModel]"
    # The three lookup tables, as data: each is a module-level dict the
    # renderer writes, three lines `gql()` reads it back with, and the Literal
    # overloads that pin what those lines hand back — differing only in the
    # fields below. Written out three times, adding a fourth kind meant
    # repeating a shape whose every field the golden files alone would have
    # caught a mistake in.
    #
    # A template is not executable, so its dict holds the class itself
    # (instantiated on lookup) rather than a shared singleton: unlike a
    # fragment handle, the class has no state to share across readers.
    tables = (
        _LookupTable(
            dict_name=dict_name,
            value_type="type[runtime.GQLOperation]",
            catch_all_type="runtime.GQLOperation",
            entries=[
                (repr(text), operation.class_name, operation.class_name)
                for operation in operations
                for text in operation.stmt_texts
            ],
            local="query_cls",
            returned="query_cls()",
        ),
        _LookupTable(
            dict_name=fragments_dict_name,
            value_type=handle_type,
            catch_all_type=handle_type,
            entries=[
                (repr(text), fragment.class_name, fragment.singleton_name)
                for fragment in fragments
                for text in fragment.stmt_texts
            ],
            local="fragment",
            returned="fragment",
        ),
        _LookupTable(
            dict_name=templates_dict_name,
            value_type="type[runtime.GQLTemplate]",
            catch_all_type="runtime.GQLTemplate",
            entries=[
                (repr(text), template.class_name, template.class_name)
                for template in templates
                for text in template.stmt_texts
            ],
            local="template_cls",
            returned="template_cls()",
        ),
    )
    # A handle is not a GQLOperation, and neither is a template, so once one of
    # them can be returned the catch-all overload has to admit it: a literal
    # overload returning a type outside the catch-all's return type is an
    # overlapping-overload error. The catch-all widens by exactly the kinds the
    # package actually contains, so a package without handles or templates keeps
    # the narrow form and `gql(some_variable)` stays as typed as it can be.
    # GQLOperation leads unconditionally: a passthrough statement returns one
    # even in a package whose every typed statement is a fragment.
    return_type = " | ".join(
        dict.fromkeys([
            "runtime.GQLOperation",
            *(table.catch_all_type for table in tables if table.entries),
        ])
    )

    def overload_line(literal: str, returned: str) -> str:
        signature = f"def {gql_fn_name}(stmt: Literal[{literal}]) -> {returned}: ..."
        return f"@overload\n{signature}"

    overloads = "\n".join([
        *(
            overload_line(literal, returned)
            for table in tables
            for literal, returned, _ in table.entries
        ),
        # Passthrough statements return the plain runtime.GQLOperation the
        # lookup actually builds for them, pinned by their own Literal
        # overloads: a package growing a handle elsewhere widens only the
        # catch-all, not these call sites.
        *(
            overload_line(repr(text), "runtime.GQLOperation")
            for text in passthrough_texts
        ),
        f"@overload\ndef {gql_fn_name}(stmt: str) -> {return_type}: ...",
    ])
    sections = [overloads]
    lookup_lines: list[str] = []
    for table in tables:
        if not table.entries:
            continue
        sections.append(table.render_dict())
        lookup_lines.extend(table.render_lookup())
    if passthrough_texts:
        # Known statements nothing typed — fragment bundles and fragments no
        # slot accepts. Their call sites legitimately receive the untyped
        # catch-all; only a statement the generator has never seen raises.
        sections.append(
            "\n".join([
                f"{passthrough_name}: frozenset[str] = frozenset({{",
                "\n".join(f"    {text!r}," for text in passthrough_texts),
                "})",
            ])
        )
        lookup_lines.extend([
            f"    if stmt in {passthrough_name}:",
            "        return runtime.GQLOperation()",
        ])

    sections.append(
        "\n".join([
            f"def {gql_fn_name}(stmt: str) -> {return_type}:",
            *lookup_lines,
            f'    msg = "unknown GraphQL statement passed to {gql_fn_name}; "',
            '    msg += "the generator only discovers bare-name calls with a "',
            '    msg += "single string literal - check the call site, then "',
            '    msg += "regenerate the package"',
            "    raise LookupError(msg)",
        ])
    )
    return "\n\n\n".join(sections)


def render_package(
    mode: GenerationMode,
    base_url_ref: ImportRef,
    package_name: str,
    gql_fn_name: str,
    collected: CollectedPackageIR,
    scalars: dict[str, ImportRef],
    to_camel_ref: ImportRef,
) -> str:
    mode_config = RENDER_MODES[mode]
    # The slot node base is only referenced by generated slot models, so a
    # package without them does not grow a class it never uses; the slot module
    # itself is also what fragment handles derive from. The open base exists
    # exactly when some model validates inside a slot or fragment subtree. A
    # template always has at least one slot (that is what makes it a template),
    # so its slot model(s) already make `uses_slot_models` true.
    uses_slot_models = next(slot_roots(collected.result_artifacts), None) is not None
    uses_open_models = bool(collected.open_model_names)
    sections = [
        # The slot model base is the one multi-base shape a module can
        # render (`GQLSlotModel(GQLOpenModel, slots.GQLSlotNode)`); a
        # fragment handle always derives from `slots.GQLFragment[Model]`
        # alone.
        render_header(unsafe_multiple_inheritance=uses_slot_models),
        render_imports(to_camel_ref, scalars, base_url_ref, mode_config),
        render_client_init(package_name, base_url_ref, to_camel_ref, mode_config),
        OPEN_BASE if uses_open_models else "",
        SLOT_BASE if uses_slot_models else "",
        "\n".join(render_enums(collected.enums)),
        "\n\n\n".join(
            render_artifacts(collected.result_artifacts, collected.open_model_names)
        ),
        "\n\n\n".join(render_artifacts(collected.input_artifacts, frozenset())),
        "\n\n\n".join(
            render_operations(collected.operations, package_name, mode_config)
        ),
        "\n\n\n".join(render_fragments(collected.fragments)),
        "\n\n\n".join(render_template_bases(collected.templates, mode_config)),
        "\n\n\n".join(render_bindings(collected.bindings, package_name, mode_config)),
        "\n\n\n".join(
            render_templates(collected.templates, collected.bindings, package_name)
        ),
        render_bind_dispatch(collected.templates, collected.bindings, package_name),
        render_gql_fn(
            collected.operations,
            collected.fragments,
            collected.templates,
            package_name,
            gql_fn_name,
            collected.passthrough_texts,
        ),
    ]
    return "\n\n\n".join(section for section in sections if section)


def render_artifacts(
    artifacts: list[CollectedArtifact], open_model_names: frozenset[str]
) -> list[str]:
    rendered: list[str] = []
    for artifact in artifacts:
        match artifact:
            case CollectedModel(slot_name=None):
                base = (
                    OPEN_MODEL_BASE_NAME
                    if artifact.name in open_model_names
                    else MODEL_BASE_NAME
                )
                rendered.append(render_pydantic_class(artifact, base))
            case CollectedModel():
                rendered.append(render_slot_class(artifact))
            case CollectedUnionAlias():
                params = (
                    f"[{', '.join(artifact.type_params)}]"
                    if artifact.type_params
                    else ""
                )
                rendered.append(f"type {artifact.name}{params} = {artifact.type_expr}")
    return rendered


def _execute_signature(variables: tuple[CollectedOperationVar, ...]) -> str:
    parts = [var.signature_part for var in variables]
    return ", ".join(["self", *(["*", *parts] if parts else [])])


def _variables_expr(
    variables: tuple[CollectedOperationVar, ...], *extra_entries: str
) -> str:
    entries = [var.variable_entry for var in variables]
    return "{" + ", ".join([*entries, *extra_entries]) + "}"


def _render_execute(
    *,
    result_type: str,
    is_subscription: bool,
    variables: tuple[CollectedOperationVar, ...],
    source_expr: str,
    variables_expr: str,
    extra_kwargs: tuple[str, ...] = (),
    package_name: str,
    mode: ModeConfig,
) -> str:
    # The one `execute` emitter: a plain operation and a template's shared base
    # differ only in where the document text comes from, what fills `variables`
    # and whether a validation context rides along -- never in how a
    # subscription is shaped or which client method answers it.
    await_kw = "" if is_subscription else mode.await_kw
    client_method = "subscribe" if is_subscription else "query"
    body = "\n".join([
        f"return {await_kw}{client_binding_name(package_name)}.{client_method}(",
        f"    {result_type},",
        f"    {source_expr},",
        f"    variables={variables_expr},",
        "    headers=self.headers,",
        *(f"    {kwarg}," for kwarg in extra_kwargs),
        ")",
    ])
    return _render_execute_signature(
        result_type=result_type,
        is_subscription=is_subscription,
        variables=variables,
        mode=mode,
        body=body,
    )


def _render_execute_signature(
    *,
    result_type: str,
    is_subscription: bool,
    variables: tuple[CollectedOperationVar, ...],
    mode: ModeConfig,
    body: str,
    decorator: str = "",
) -> str:
    # A subscription's execute hands back the context manager the client
    # returns, so it is never awaited and never declared async in either mode.
    if is_subscription:
        async_kw = ""
        return_type = f"{mode.stream_context}[{mode.generator}[{result_type}]]"
    else:
        async_kw = mode.async_kw
        return_type = result_type
    signature_line = (
        f"{async_kw}def execute({_execute_signature(variables)}) -> {return_type}:"
    )
    lines = [*([decorator] if decorator else []), signature_line]
    return "\n".join([*lines[:-1], f"{lines[-1]}\n    {indent_block(body, '    ')}"])


def render_operations(
    operations: list[CollectedOperation],
    package_name: str,
    mode: ModeConfig,
) -> list[str]:
    rendered: list[str] = []
    for operation in operations:
        execute = _render_execute(
            result_type=operation.result_type,
            is_subscription=operation.is_subscription,
            variables=operation.variables,
            source_expr=repr(operation.exec_source),
            variables_expr=_variables_expr(operation.variables),
            package_name=package_name,
            mode=mode,
        )
        rendered.append(
            "\n".join([
                f"class {operation.class_name}(runtime.GQLOperation):",
                f"    # See: {', '.join(operation.locations)}",
                f"    {indent_block(execute, '    ')}",
            ])
        )
    return rendered


def render_template_bases(
    templates: list[CollectedTemplate], mode: ModeConfig
) -> list[str]:
    # A template is not executable on its own -- only a binding of it (below)
    # pins `exec_source__`/`slot_handles__` and its own result type -- so what
    # lives here is the shape every binding of one template shares: one type
    # parameter, the result, and the `execute` signature written against it.
    #
    # The parameter is the *result*, one for the whole base, while the slot
    # phantoms live on the models (see `collect.parametrize_slot_paths`) and
    # each binding fills them in when it names its result type. The two say
    # different things: this one lets a helper generic over
    # `{Operation}Bound[TResult]` take any binding of the template and hand its
    # caller back the concrete result, while the phantoms let a helper that
    # names `{Operation}Result[Any]` read a slot with the handle it was
    # passed.
    rendered: list[str] = []
    for template in templates:
        # The parameter carries no bound: the base never validates anything
        # itself -- `execute` is a declaration here -- and a bound would force
        # every caller writing a helper over `{Operation}Bound[TResult]` to
        # spell the generated model base in their own signature.
        header = (
            f"class {template.bound_base_name}[{BOUND_RESULT_PARAM}]"
            "(runtime.GQLBoundOperation, ABC):"
        )
        body = _render_template_execute_stub(template, mode)
        rendered.append(f"{header}\n    {indent_block(body, '    ')}")
    return rendered


def _render_template_execute_stub(template: CollectedTemplate, mode: ModeConfig) -> str:
    # The signature a caller sees on the base, with the body left to each
    # binding: only a binding knows which result model answers for it.
    return _render_execute_signature(
        result_type=BOUND_RESULT_PARAM,
        is_subscription=template.is_subscription,
        variables=template.variables,
        mode=mode,
        # `...` rather than a raise: this is a declaration, and `abstractmethod`
        # is what tells a reader -- and the type checker -- that the parameters
        # are named for the implementations rather than ignored here.
        body="...",
        decorator="@abstractmethod",
    )


def _slot_handle_expr(handle: CollectedSlotHandle) -> str:
    typenames = ", ".join(repr(name) for name in handle.typenames)
    singleton = handle.fragment.singleton_name
    return f"slots.SlotHandle({singleton}, frozenset({{{typenames}}}))"


def _slot_handles_expr(binding: CollectedBinding) -> str:
    # The whole readable set, wider than `direct_fragments`: a fragment this
    # slot's bind reaches through another fragment's root-level spread must be
    # offered to `validate_slot__` too, so it becomes independently readable
    # and boundary-validated. Each carries the typenames it is reachable at --
    # which a narrowing spread cuts below the fragment's own type condition.
    # Feeds `execute()`'s validation context.
    entries = ", ".join(
        f'"{bslot.slot.name}": '
        + _tuple_literal(
            tuple(_slot_handle_expr(handle) for handle in bslot.readable_handles)
        )
        for bslot in binding.slots
    )
    return "{" + entries + "}"


def _tuple_literal(items: tuple[str, ...]) -> str:
    if not items:
        return "()"
    if len(items) == 1:
        return f"({items[0]},)"
    return f"({', '.join(items)})"


def _arg_signature_part(arg: CollectedBindingArg) -> str:
    # A synthesized fragment variable never carries a literal GraphQL default
    # (`expand_binding` always emits `default_value=None` on the node), so the
    # Python default is supplied here for exactly the omittable ones.
    if arg.omittable:
        return f"{arg.var.signature_part} = None"
    return arg.var.signature_part


def _arg_variable_entry(arg: CollectedBindingArg) -> str:
    # Dropping the key *is* the meaning for an omittable variable, so its
    # entry splices in only when the caller passed something.
    if arg.omittable:
        return (
            f"**({{{arg.var.variable_entry}}} "
            f"if {arg.var.python_name} is not None else {{}})"
        )
    return arg.var.variable_entry


def _render_with_args(binding: CollectedBinding) -> str | None:
    # `with_args` builds its variables the same way `execute` does: every
    # declared variable goes into the dict, so passing `None` sends an
    # explicit null rather than silently dropping the variable and letting the
    # server's default win. The one exception is the omittable set, where
    # dropping the key *is* the meaning — every position those variables fill
    # declares a schema default, and an absent variable is the only spelling
    # that lets it apply (a non-null position rejects an explicit null
    # outright). Both spellings come off `CollectedBindingArg`, which is what
    # carries the distinction.
    #
    # The whole mapping is one expression so the body binds no local name:
    # anything it bound would join `with_args()`'s parameter namespace and
    # collide with a fragment variable that happens to snake to it.
    if not binding.arg_vars:
        return None
    params = ", ".join(_arg_signature_part(arg) for arg in binding.arg_vars)
    entries = ", ".join(_arg_variable_entry(arg) for arg in binding.arg_vars)
    return "\n".join([
        f"def with_args(self, *, {params}) -> Self:",
        f"    return self.with_args__({{{entries}}})",
    ])


def render_bindings(
    bindings: list[CollectedBinding], package_name: str, mode: ModeConfig
) -> list[str]:
    rendered: list[str] = []
    for binding in bindings:
        class_expr = (
            f"{binding.class_name}"
            f"({binding.template.bound_base_name}[{binding.result_type}])"
        )
        header = f"class {class_expr}:"
        body_lines = [
            # The call sites, the same way an operation carries its own: a
            # binding is named after its combination, so this comment is what
            # leads a reader from the generated class back to the `.bind(...)`
            # calls that produced it.
            f"# See: {', '.join(binding.locations)}",
            f"exec_source__ = {binding.exec_source!r}",
            f"slot_handles__ = {_slot_handles_expr(binding)}",
        ]
        with_args = _render_with_args(binding)
        if with_args is not None:
            required_literal = ", ".join(
                repr(name) for name in binding.required_arg_names
            )
            body_lines.extend([
                f"required_arg_names__ = frozenset({{{required_literal}}})",
                with_args,
            ])
        # `execute` is written per binding rather than once on the base: the
        # class handed to the client is this binding's own result model, and a
        # body inherited from a generic base is evaluated with the base's own
        # type parameter -- Python substitutes nothing there, so the client
        # would receive the TypeVar itself.
        body_lines.append(
            "@override\n" + _render_binding_execute(binding, package_name, mode)
        )
        body = "\n".join(body_lines)
        rendered.append(f"{header}\n    {indent_block(body, '    ')}")
    return rendered


def _render_binding_execute(
    binding: CollectedBinding, package_name: str, mode: ModeConfig
) -> str:
    template = binding.template
    return _render_execute(
        result_type=binding.result_type,
        is_subscription=template.is_subscription,
        variables=template.variables,
        source_expr="self.exec_source__",
        # A template's own variables plus whatever the binding's fragments
        # required -- pinned per binding via `with_args`/`with_args__`, read
        # back here through the shared `fragment_args__()` accessor.
        variables_expr=_variables_expr(template.variables, "**self.fragment_args__()"),
        extra_kwargs=("slot_handles=self.slot_handles__",),
        package_name=package_name,
        mode=mode,
    )


def _bind_key_tuple(binding: CollectedBinding) -> BindKey:
    # Built through the shared shape (see `slots.bind_key_shape`), so the
    # literal rendered here and the key the runtime computes from the handles
    # a caller passes cannot drift apart. Slots are named by the kwarg the
    # caller writes (`python_name`), the same name `bind()`'s parameters use.
    return bind_key_shape(
        binding.template.class_name,
        (
            (
                bslot.slot.python_name,
                (fragment.fragment_name for fragment in bslot.direct_fragments),
            )
            for bslot in binding.slots
        ),
    )


def render_bind_dispatch(
    templates: list[CollectedTemplate],
    bindings: list[CollectedBinding],
    package_name: str,
) -> str:
    # Every template's `bind()` body references this name unconditionally
    # (see `_bind_fallback` and `_bind_single_binding_impl`), even a template
    # with no bindings of its own — so the dict is rendered whenever a
    # template exists, not only when a binding does; an empty dict answers
    # every lookup with `None`.
    if not templates:
        return ""
    dispatch_name = _module_dict_name(package_name, "BIND_DISPATCH")

    def entry(binding: CollectedBinding) -> str:
        return f"    {_bind_key_tuple(binding)!r}: {binding.class_name},"

    entries = "\n".join(entry(binding) for binding in bindings)
    return "\n".join([
        f"{dispatch_name}: dict[slots.BindKey, type[runtime.GQLBoundOperation]] = {{",
        entries,
        "}",
    ])


def _bind_param(binding_slot: CollectedBindingSlot) -> str:
    # The type of the value(s) a caller actually passes to bind() for this one
    # slot -- the fragment handle class(es) (e.g. `ImageParts`), as opposed to
    # the model each fragment's own `read(node)` hands back. Three cases, one
    # per arity of the slot's directly-bound fragments.
    name = binding_slot.slot.python_name
    match [fragment.class_name for fragment in binding_slot.direct_fragments]:
        case []:
            # `Sequence[Never]` is inhabited by exactly one value, the empty
            # sequence, so this both types an explicit `slot=[]` and (via the
            # default) lets the slot be omitted entirely -- the two spellings
            # the README documents as meaning the same thing. The `= ()`
            # default is also load-bearing for `reportOverlappingOverload`:
            # every parameter of every overload needs a value it can be called
            # without, so an all-defaulted overload (all-unfilled binding) is
            # reachable as `bind()`, and pyright can compare two overloads'
            # domains as ordinary unions instead of tripping over one
            # requiring an argument the other doesn't.
            return f"{name}: Sequence[Never] = ()"
        case [only]:
            # A slot filled by exactly one fragment accepts both calling
            # conventions at once -- the bare handle or a one-element Sequence
            # of it (both produce the same `bind_key`) -- as a union type,
            # rather than as two separate overloads.
            return f"{name}: {only} | Sequence[{only}]"
        case classes:
            # A slot filled by several fragments has no bare spelling: one
            # bare value cannot stand for several fragments, whatever the
            # other slots look like.
            return f"{name}: Sequence[{' | '.join(classes)}]"


def _bind_overload_lines(bindings: list[CollectedBinding]) -> list[str]:
    # One overload per binding, spanning every slot of the template, not just
    # the ones this binding fills: a slot this binding leaves unfilled still
    # gets a parameter, typed `Sequence[Never] = ()`, so a caller can spell
    # "no fragments for this slot" either by omitting the kwarg or by passing
    # `[]` and land on the same binding either way — without
    # this, `[]` for a slot this binding leaves unfilled would only match
    # some *other* binding's wider `Sequence[Fragment]` overload for that
    # same slot, and the caller would get back a value of the wrong binding
    # class. The same default also reaches an all-unfilled binding through a
    # bare `bind()` call, with no separate zero-kwarg overload needed.
    #
    # Each filled slot's parameter is a union of both calling conventions
    # (see `_bind_param`), so every slot of a binding picks its own
    # spelling independently -- a mixed call like
    # `bind(attachment=image_parts, preview=[image_parts])` type-checks
    # without a dedicated overload for that combination.
    #
    # Overloads sort by ascending total fragment count (stable on ties, so
    # equal-count bindings keep their (file, lineno) discovery order). A
    # binding with more unfilled (Sequence[Never]) slots has a lower total,
    # so its overload is tried first -- exactly what makes `bind(slot=[])`
    # resolve to the binding that leaves `slot` unfilled rather than to a
    # filled binding whose broader `Sequence[Fragment]` also accepts `[]`.
    def total_fragments(binding: CollectedBinding) -> int:
        return sum(len(bslot.direct_fragments) for bslot in binding.slots)

    return [
        "@overload\ndef bind(self, *, "
        + ", ".join(_bind_param(bslot) for bslot in binding.slots)
        + f") -> {binding.class_name}: ..."
        for binding in sorted(bindings, key=total_fragments)
    ]


# Shared by `_bind_fallback` and `_bind_single_binding_impl`: both raise the
# same "no discovered combination" diagnostic from inside an `if ... is
# None:` block at 4-space (function-body) indent, so one copy of the message
# can't drift from the other.
#
# One expression, binding no local: every name a rendered body binds joins the
# enclosing method's keyword namespace, where a GraphQL name that happens to
# snake to it would collide -- and `naming._signature_claims` would then have
# to reserve it, which is a second, hand-maintained copy of what this function
# writes. The generated module suppresses formatting and linting wholesale
# (see `render_header`), so the length of the one line this produces is
# nobody's business but this comment's.
def _bind_lookup_error_line(template_class_name: str) -> str:
    message = (
        f"unknown bind combination for {template_class_name}; every fragment "
        "a bind passes must be a discovered statement - check the call site, "
        "then regenerate the package"
    )
    return f'        raise LookupError("{message}")'


def _bind_fallback(template: CollectedTemplate, package_name: str) -> str:
    # The implementation under the overload stubs. Its parameters are the
    # template's own slots, spelled out, rather than `**fragments`: a keyword
    # that names no slot is then rejected by the interpreter itself, at the
    # call, with the name it was written as. Collected into `**fragments` it
    # reached `bind_key`, where a slot passed nothing is normalised away --
    # so a misspelled slot passed nothing produced the key of a call that
    # named nothing at all, and answered with whatever binding that is.
    dispatch_name = _module_dict_name(package_name, "BIND_DISPATCH")
    handle_type = "slots.GQLFragment[pydantic.BaseModel]"
    params = ", ".join(
        f"{slot.python_name}: {handle_type} | Sequence[{handle_type}] = ()"
        for slot in template.slots
    )
    fragments_dict = ", ".join(
        f"{slot.python_name!r}: {slot.python_name}" for slot in template.slots
    )
    bind_key_expr = f"slots.bind_key({template.class_name!r}, {{{fragments_dict}}})"
    # The lookup is written twice rather than kept in a local: a local joins
    # this method's keyword namespace, where a slot that snakes to the same
    # spelling would land on it (see `_bind_lookup_error_line`). It did -- a
    # `cls` local took the parameter of a slot called `cls`, and the module
    # still ran, because the key is built before the name is rewritten, while
    # a type checker read the rest of the body against the parameter's type.
    # The dispatch is a dict, so the second lookup costs a hash.
    return "\n".join([
        f"def bind(self, *, {params}) -> runtime.GQLBoundOperation:",
        f"    if {dispatch_name}.get({bind_key_expr}) is None:",
        _bind_lookup_error_line(template.class_name),
        f"    return {dispatch_name}[{bind_key_expr}]()",
    ])


# (name, what claims it) for every name `_bind_single_binding_impl`'s rendered
# body reads from an enclosing scope and spells the same way in every package.
# Declared here, where that body is written, and consumed by
# `naming._signature_claims`, which reserves them against a GraphQL variable
# that happens to snake to one -- a second hand-maintained list over there
# would go stale the day the body reads one more module. The body binds no
# local of its own (see `_bind_lookup_error_line`).
#
# The body reads one more enclosing name, the package's bind dispatch dict,
# and that one is deliberately absent: `_module_dict_name` spells it after the
# package (`_{PACKAGE}_GQL_BIND_DISPATCH`), so it is no constant this tuple
# could hold -- and a parameter could only shadow it if `to_snake_fn` returned
# an upper-case name with a leading underscore, which is not a spelling a
# snake-case transform produces. Its module-scope claim, where the collision
# is real, sits with the other dicts' in `scaffold_claims`.
BIND_BODY_FREE_NAMES: tuple[tuple[str, str], ...] = (
    ("slots", "the iron_gql slots module"),
)


def _bind_overloads(
    template: CollectedTemplate, bindings: list[CollectedBinding]
) -> list[str]:
    # Every discovered binding's signature, and -- when they do not add up to
    # the two `@overload` needs -- the signature for the calls no binding
    # matches, returning `Never` because such a call raises `LookupError`.
    #
    # Writing the missing signature is what lets `bind()` have one form.
    # A template with a single binding used to be rendered as one plain
    # signature instead, and the difference was not confined to typing: that
    # binding's filled slots became required parameters, so `bind()` raised
    # `TypeError` before reaching the dispatch while `bind(slot=[])` reached
    # the documented `LookupError` -- two answers to what README.md calls one
    # thing, and which one a call got depended on how many combinations the
    # tree happened to hold.
    #
    # The empty-call signature is written whenever no binding leaves every
    # slot unfilled, however many bindings there are: a bare `bind()` must
    # answer the same way whether the tree holds one combination or five, and
    # `Never` is that answer wherever the combination is missing. It goes
    # first because it is the narrower -- overload resolution takes the first
    # match, and a filled binding's `Sequence[Fragment]` would otherwise
    # swallow `[]`.
    #
    # The filled-call signature is the mirror image, and is only ever needed
    # to reach two signatures: it accepts anything, so it must come last, and
    # writing it while a real binding's stub is also present would overlap
    # that stub with an incompatible return type.
    # `@overload` needs at least this many signatures; pyright rejects a lone
    # one, which is the whole reason the second form used to exist.
    minimum_overloads = 2
    discovered = _bind_overload_lines(bindings)
    binds_nothing_combination = any(
        all(not bslot.direct_fragments for bslot in binding.slots)
        for binding in bindings
    )
    stubs = (
        discovered
        if binds_nothing_combination
        else [
            _never_stub(template, empty=True),
            *discovered,
        ]
    )
    if len(stubs) >= minimum_overloads:
        return stubs
    return [*stubs, _never_stub(template, empty=False)]


def _never_stub(template: CollectedTemplate, *, empty: bool) -> str:
    # The signature for calls this template has no binding for: every slot
    # left empty, or every slot filled by anything at all.
    handle = "slots.GQLFragment[pydantic.BaseModel]"
    spelling = "Sequence[Never] = ()" if empty else f"{handle} | Sequence[{handle}]"
    params = ", ".join(f"{slot.python_name}: {spelling}" for slot in template.slots)
    return f"@overload\ndef bind(self, *, {params}) -> Never: ..."


def render_templates(
    templates: list[CollectedTemplate],
    bindings: list[CollectedBinding],
    package_name: str,
) -> list[str]:
    # The bare per-template dispatcher: one `@overload` per discovered
    # binding over one implementation, whatever the number of bindings. The
    # signatures say which combinations exist; the implementation answers
    # every call the same way, by looking the combination up.
    grouped = bindings_by_template(bindings)
    rendered: list[str] = []
    for template in templates:
        template_bindings = grouped.get(template.class_name, [])
        overload_lines = _bind_overloads(template, template_bindings)
        body = "\n".join([*overload_lines, _bind_fallback(template, package_name)])
        header = f"class {template.class_name}(runtime.GQLTemplate):"
        rendered.append(f"{header}\n    {indent_block(body, '    ')}")
    return rendered


def render_enums(enums: list[CollectedEnum]) -> list[str]:
    return [
        f"type {enum.name} = Literal[{', '.join(repr(value) for value in enum.values)}]"
        for enum in enums
    ]
