import itertools
from dataclasses import dataclass
from typing import Literal

from iron_gql.codegen.ir import CollectedArtifact
from iron_gql.codegen.ir import CollectedBinding
from iron_gql.codegen.ir import CollectedEnum
from iron_gql.codegen.ir import CollectedFactoryFragment
from iron_gql.codegen.ir import CollectedField
from iron_gql.codegen.ir import CollectedFragment
from iron_gql.codegen.ir import CollectedFragmentArg
from iron_gql.codegen.ir import CollectedModel
from iron_gql.codegen.ir import CollectedOmittableFragmentArg
from iron_gql.codegen.ir import CollectedOnTypeBase
from iron_gql.codegen.ir import CollectedOperation
from iron_gql.codegen.ir import CollectedOperationVar
from iron_gql.codegen.ir import CollectedPackageIR
from iron_gql.codegen.ir import CollectedPlainFragment
from iron_gql.codegen.ir import CollectedReadableFragment
from iron_gql.codegen.ir import CollectedRequiredFragmentArg
from iron_gql.codegen.ir import CollectedTemplate
from iron_gql.codegen.ir import CollectedTemplateSlot
from iron_gql.codegen.ir import CollectedUnionAlias
from iron_gql.codegen.ir import ImportRef
from iron_gql.codegen.ir import field_name_to_pascal
from iron_gql.codegen.ir import render_type_expr
from iron_gql.codegen.ir import slot_roots
from iron_gql.codegen.util import indent_block


def render_header(*, unsafe_multiple_inheritance: bool) -> str:
    # `reportUnsafeMultipleInheritance` выключается только для module с
    # multi-base slot model. Fragment definition всегда наследует один
    # `slots.GQLFragment[Model, Reads]` base и этого suppression не требует.
    suppressions = "reportUnusedImport=false"
    if unsafe_multiple_inheritance:
        suppressions += ", reportUnsafeMultipleInheritance=false"
    return f"""\
from __future__ import annotations
# Code generated by iron_gql, DO NOT EDIT.
# fmt: off
# pyright: {suppressions}
# ruff: noqa"""


# The module-level names the scaffold binds, kept in one place because
# `scaffold_claims` hands the same set to the collision rule and everything
# below renders from these very names. Each tuple is already sorted: the import
# blocks are emitted in this order.
MODEL_BASE_NAME = "GQLModel"
OPEN_MODEL_BASE_NAME = "GQLOpenModel"
SLOT_MODEL_BASE_NAME = "GQLSlotModel"
BASE_CLASS_NAMES = (MODEL_BASE_NAME, OPEN_MODEL_BASE_NAME, SLOT_MODEL_BASE_NAME)
STDLIB_MODULE_NAMES = ("datetime", "typing")
# Imported unconditionally and referenced by every model, so it is reserved
# unconditionally too — deriving the claim from `to_camel_ref` instead would
# drop it as soon as a package points that option somewhere other than pydantic.
THIRD_PARTY_MODULE_NAMES = ("pydantic",)
# Both modes' names are reserved whichever mode a package is generated in: the
# reserved set must not depend on the mode in force today, or switching a
# package to the other mode would rebind a name that generated fine before.
CONTEXTLIB_NAMES = ("AbstractAsyncContextManager", "AbstractContextManager")
GENERATOR_NAMES = ("AsyncGenerator", "Generator")
ABC_NAMES = (*GENERATOR_NAMES, "Callable", "Sequence")
ABC_MODULE_NAMES = ("ABC", "abstractmethod")
# An unfilled slot spells `Never` twice over -- as its node's phantom
# (`render_slot_class`) and as the element type of its `bind()` parameter
# (`EMPTY_SLOT_FORM`). `typing.cast` is the one point where a template's shared
# bound class reconciles the result type `bind()`'s overload promised with the
# one runtime class every combination actually validates against
# (`_render_template_bound_execute`).
TYPING_NAMES = (
    "Annotated",
    "Any",
    "ClassVar",
    "Literal",
    "Never",
    "TypeVar",
    "final",
    "overload",
    "override",
)
IRON_GQL_NAMES = ("runtime", "slots")
# The one name in this block the module never binds: it is a PEP 695 parameter
# written *inside* a template's bound base (`render_template_bases`), where it
# shadows a module-level model or enum spelled the same. `execute`'s variable
# annotations are rendered in that scope, so a schema with an `input TResult`
# used as a template variable makes the base read `TResult` as its own
# parameter while `bind()`'s own overloads read the model -- a package that
# generates cleanly and then fails to type-check. Reserved rather than renamed
# out of the way: every name a parameter could take is a name a schema can
# spell, so only a claim closes the case.
BOUND_RESULT_PARAM = "TResult"
# The two parameters every `On{Type}` base (below) is generic over: one pair
# of module-level TypeVars, reused across every base rather than declared
# fresh per class, mirroring `slots.GQLFragment`'s own `TModel_co`/
# `TReads_contra` and for the same reason (PEP 695 cannot declare variance,
# and the second parameter needs a contravariant `default=Never`). A class
# that merely mentions a free TypeVar in its base expression is generic over
# it without declaring its own -- old-style generics have always worked this
# way -- so every `On{Type}` base ends up parametrised by exactly this pair.
TMODEL_PARAM = "TModel"
TREADS_PARAM = "TReads"


# A slot payload carries every passed fragment's fields next to the static
# selection, and a fragment validates that same payload for its own fields —
# so every model validating inside a slot or fragment subtree ignores the
# keys other readers asked for instead of forbidding them. Isolation is not
# lost: a model exposes only the fields its own selection declared.
OPEN_BASE = f"""\
class {OPEN_MODEL_BASE_NAME}({MODEL_BASE_NAME}):
    model_config = pydantic.ConfigDict(extra="ignore")"""

_SLOT_BASES = f"{OPEN_MODEL_BASE_NAME}, slots.GQLSlotNode[TOffered]"
# `TOffered` is a PEP 695 parameter that does nothing but pass through to the
# contravariant phantom of `slots.GQLSlotNode`, which is where its variance
# comes from: a node offering more fragments stays acceptable where fewer are
# expected. Unlike `BOUND_RESULT_PARAM` it claims nothing: this base's body is
# `pass`, so there is no module-level name it could shadow.
SLOT_BASE = f"""\
class {SLOT_MODEL_BASE_NAME}[TOffered]({_SLOT_BASES}):
    pass"""

# Declared once, ahead of every `On{Type}` base (`render_on_type_bases`),
# which all reuse this exact pair -- see `TMODEL_PARAM`/`TREADS_PARAM`'s own
# comment for why they are module-level TypeVars rather than a PEP 695
# declaration repeated per base.
ON_TYPE_TYPEVARS = f"""\
{TMODEL_PARAM} = TypeVar("{TMODEL_PARAM}", bound=pydantic.BaseModel, covariant=True)
{TREADS_PARAM} = TypeVar("{TREADS_PARAM}", contravariant=True)"""


type GenerationMode = Literal["async", "sync"]


@dataclass(frozen=True, slots=True)
class ModeConfig:
    client_class: str
    async_kw: str
    await_kw: str
    stream_context: str
    generator: str


RENDER_MODES: dict[GenerationMode, ModeConfig] = {
    "async": ModeConfig(
        client_class="AsyncGQLClient",
        async_kw="async ",
        await_kw="await ",
        stream_context="AbstractAsyncContextManager",
        generator="AsyncGenerator",
    ),
    "sync": ModeConfig(
        client_class="GQLClient",
        async_kw="",
        await_kw="",
        stream_context="AbstractContextManager",
        generator="Generator",
    ),
}


def scaffold_claims(
    *,
    gql_fn_name: str,
    base_url_ref: ImportRef,
    scalars: dict[str, ImportRef],
    to_camel_ref: ImportRef,
) -> dict[str, tuple[str, ...]]:
    # Names only imported when a package uses slots or fragments are listed
    # unconditionally: the reserved set must not depend on which optional
    # features a package happens to use today, or adding a slot to it would
    # rebind a name that generated fine a commit earlier.
    #
    # Each binding keeps its origin so the collision rule can tell two
    # scaffold sources fighting over one name apart from one binding listed
    # twice: identical origins (the same import statement reached from two
    # configs, e.g. `import pydantic`) collapse into a single claim, while
    # different origins for one name are a real collision.
    pairs: list[tuple[str, str]] = [
        *((name, "the generated model base class") for name in BASE_CLASS_NAMES),
        *((module, f"import {module}") for module in STDLIB_MODULE_NAMES),
        *((module, f"import {module}") for module in THIRD_PARTY_MODULE_NAMES),
        *((name, f"from contextlib import {name}") for name in CONTEXTLIB_NAMES),
        *((name, f"from collections.abc import {name}") for name in ABC_NAMES),
        *((name, f"from abc import {name}") for name in ABC_MODULE_NAMES),
        *((name, f"from typing import {name}") for name in TYPING_NAMES),
        *((name, f"from iron_gql import {name}") for name in IRON_GQL_NAMES),
        (BOUND_RESULT_PARAM, "the type parameter of a template's bound base"),
        (TMODEL_PARAM, "the model type parameter of every on-type base"),
        (TREADS_PARAM, "the readable-closure type parameter of every on-type base"),
        (gql_fn_name, "the generated gql function"),
        ("_client", "the generated client binding"),
        ("_statement_factories", "the generated statement factory table"),
        (base_url_ref.root_symbol, base_url_ref.import_statement()),
        (to_camel_ref.root_module, f"import {to_camel_ref.root_module}"),
        *((ref.root_module, f"import {ref.root_module}") for ref in scalars.values()),
    ]
    claims: dict[str, dict[str, None]] = {}
    for name, origin in pairs:
        claims.setdefault(name, {})[origin] = None
    return {name: tuple(origins) for name, origins in claims.items()}


def render_field(field: CollectedField) -> str:
    rendered_type = render_type_expr(field.rendered_type)
    default_expr = field.default_expr
    if field.is_conditional and default_expr is None:
        default_expr = "None"

    if field.alias is not None:
        rendered_type = (
            f"Annotated[{rendered_type}, "
            f'pydantic.Field(validation_alias="{field.alias}", '
            f'serialization_alias="{field.alias}")]'
        )
    if default_expr is not None:
        return f"{field.name}: {rendered_type} = {default_expr}"
    return f"{field.name}: {rendered_type}"


def render_pydantic_class(model: CollectedModel, base: str) -> str:
    rendered_fields = "\n".join(render_field(field) for field in model.fields)
    header = f"class {model.name}{_type_params(model.type_params)}({base}):"
    return f"{header}\n    {indent_block(rendered_fields, '    ')}"


def render_slot_class(model: CollectedModel) -> str:
    # A node model is the phantom's one destination: the parameter threaded
    # down the path to it lands here, in the slot base, and each binding fills
    # it with the fragment classes readable at this slot.
    if not model.type_params:
        # Internal invariant: a node model is its own slot's model, and
        # `collect.parametrize_slot_paths` seeds the walk with exactly those.
        msg = f"slot node {model.name!r} reached the renderer unparametrised"
        raise AssertionError(msg)
    offered = ", ".join(model.type_params)
    body = "\n".join([
        f'slot_name__: ClassVar[str] = "{model.slot_name}"',
        *(render_field(field) for field in model.fields),
    ])
    header = (
        f"class {model.name}{_type_params(model.type_params)}"
        f"({SLOT_MODEL_BASE_NAME}[{offered}]):"
    )
    return f"{header}\n    {indent_block(body, '    ')}"


def _type_params(type_params: tuple[str, ...]) -> str:
    # PEP 695 parameters, declared on the model itself: their order is the
    # model's own statement, which a parametrised base cannot make when the
    # model reaches two slots. Variance is left to inference and lands where it
    # belongs -- a parameter that only reaches `slots.GQLSlotNode`'s
    # contravariant phantom infers contravariant, one behind a `list[...]`
    # field infers invariant, and invariant is the truth for a mutable field.
    # Shared code that wants any binding's result spells the phantom `Any`,
    # which is assignable both ways whatever the variance came out as.
    #
    # The parameters are visible in pydantic's JSON Schema -- `$defs` keys and
    # titles carry the fragment class names (`Post_ImageParts_`) -- so two
    # bindings of one template describe the same shape under two names. The
    # phantom is not a field and nothing validates by it; a consumer diffing
    # schema snapshots is the one this shows up for.
    if not type_params:
        return ""
    # Each defaults to `Never` (PEP 696), so the bare `{Op}Result` an
    # annotation may still spell means "readable by nothing" rather than an
    # unparametrised generic -- the same bottom `slots.GQLSlotNode` declares
    # for its own phantom.
    defaulted = ", ".join(f"{name} = Never" for name in type_params)
    return f"[{defaulted}]"


def render_imports(
    to_camel_ref: ImportRef,
    scalars: dict[str, ImportRef],
    base_url_ref: ImportRef,
    mode: ModeConfig,
) -> str:
    import_modules = [ref.module for ref in scalars.values()]
    scalar_imports = "\n".join(f"import {module}" for module in import_modules)
    # Every fixed name is emitted whole, whichever features the package
    # happens to use: the module suppresses unused imports, so an extra line
    # costs nothing, while a predicate that drifts from the emitter that
    # writes the name costs a NameError in generated code -- and
    # `scaffold_claims` already reserves the same names unconditionally for
    # exactly that reason. Only the mode-owned pairs are a choice, and
    # `ModeConfig` is what chooses.
    abc_imports = "\n".join(
        f"from collections.abc import {name}"
        for name in ABC_NAMES
        if name not in GENERATOR_NAMES or name == mode.generator
    )
    abc_module_imports = "\n".join(
        f"from abc import {name}" for name in ABC_MODULE_NAMES
    )
    typing_imports = "\n".join(f"from typing import {name}" for name in TYPING_NAMES)
    iron_gql_imports = "\n".join(
        f"from iron_gql import {name}" for name in IRON_GQL_NAMES
    )
    stdlib_imports = "\n".join(f"import {module}" for module in STDLIB_MODULE_NAMES)
    contextlib_imports = f"from contextlib import {mode.stream_context}"
    third_party_imports = "\n".join(
        f"import {module}" for module in THIRD_PARTY_MODULE_NAMES
    )
    return f"""\
{stdlib_imports}
{abc_module_imports}
{abc_imports}
{contextlib_imports}
{typing_imports}

{third_party_imports}

{iron_gql_imports}

import {to_camel_ref.module}

{scalar_imports}

{base_url_ref.import_statement()}"""


def render_client_init(
    base_url_ref: ImportRef,
    to_camel_ref: ImportRef,
    mode: ModeConfig,
) -> str:
    return f"""\
_client = runtime.{mode.client_class}(
    base_url={base_url_ref.symbol},
)


class {MODEL_BASE_NAME}(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True,
        serialize_by_alias=True,
        alias_generator=pydantic.AliasGenerator(
            validation_alias={to_camel_ref.dotted_path},
            serialization_alias={to_camel_ref.dotted_path},
        ),
        extra="forbid",
        validate_default=True,
    )"""


def render_on_type_bases(bases: list[CollectedOnTypeBase]) -> list[str]:
    # Плоские abstract bases не наследуются друг от друга. Они описывают только
    # тип допустимого fragment reader для GraphQL type condition; concrete fragment
    # фиксирует metadata в собственном constructor.
    on_type_base = f"slots.GQLBindableFragment[{TMODEL_PARAM}, {TREADS_PARAM}], ABC"
    body = "\n".join([
        "@abstractmethod",
        "def __init__(",
        "    self,",
        "    *,",
        "    fragment_name: str,",
        "    definition_type: type[slots.GQLFragment[",
        f"        {TMODEL_PARAM}, {TREADS_PARAM},",
        "    ]],",
        f"    adapter: pydantic.TypeAdapter[{TMODEL_PARAM}],",
        ") -> None:",
        "    super().__init__(",
        "        fragment_name=fragment_name,",
        "        definition_type=definition_type,",
        "        adapter=adapter,",
        "    )",
    ])
    return [
        f"class {base.name}({on_type_base}):\n    {indent_block(body, '    ')}"
        for base in bases
    ]


def _arg_signature_part(arg: CollectedFragmentArg) -> str:
    type_expr = render_type_expr(arg.explicit_value_type)
    match arg:
        case CollectedRequiredFragmentArg():
            return f"{arg.python_name}: {type_expr}"
        case CollectedOmittableFragmentArg():
            return f"{arg.python_name}: {type_expr} | slots.Omitted = slots.OMITTED"


def _arg_variable_entry(arg: CollectedFragmentArg) -> str:
    variable_entry = f'"{arg.gql_name}": {arg.python_name}'
    match arg:
        case CollectedRequiredFragmentArg():
            return variable_entry
        case CollectedOmittableFragmentArg():
            return (
                f"**({{{variable_entry}}} "
                f"if {arg.python_name} is not self._omitted__ else {{}})"
            )


def _render_applied_init(fragment: CollectedFactoryFragment) -> str:
    return "\n".join([
        "@override",
        "def __init__(self, fragment_args: dict[str, object], /) -> None:",
        "    super().__init__(",
        f"        fragment_name={fragment.fragment_name!r},",
        f"        definition_type={fragment.class_name},",
        f"        adapter={fragment.class_name}.adapter__,",
        "    )",
        "    self._set_fragment_args(fragment_args)",
    ])


def _render_public_fragment_init(fragment: CollectedFragment) -> str:
    return "\n".join([
        "@override",
        "def __init__(self) -> None:",
        "    super().__init__(",
        f"        fragment_name={fragment.fragment_name!r},",
        f"        definition_type={fragment.class_name},",
        "        adapter=self.adapter__,",
        "    )",
    ])


def _render_with_args(fragment: CollectedFactoryFragment) -> str:
    params = ", ".join(_arg_signature_part(arg) for arg in fragment.arg_vars)
    entries = ", ".join(_arg_variable_entry(arg) for arg in fragment.arg_vars)
    return "\n".join([
        f"def with_args(self, *, {params}) -> {fragment.applied_class_name}:",
        f"    return {fragment.applied_class_name}({{{entries}}})",
    ])


def render_fragments(fragments: list[CollectedFragment]) -> list[str]:
    # Plain definition наследуется от своего on-type base (`render_on_type_bases`):
    # это имя использует совместимый overload `bind()`, а второй аргумент —
    # readable closure самого фрагмента. Он записан forward-ref строкой, потому
    # что всегда включает определяемый reader class. Factory definition
    # наследуется прямо от `slots.GQLFragment`, минуя on-type base: без
    # application её нельзя передать в `bind()`.
    #
    # Definition и application одной factory получают один `bound_closure`:
    # private applied class плюс transitive readers. Поэтому оба значения
    # читают один projection, а существующие tuple constraints продолжают
    # выводить точные application types.
    #
    # Один TypeAdapter хранится на public definition class и переиспользуется
    # всеми definition values и applications. Identity задаёт сам generated
    # class (`definition_type`), не adapter и не instance.
    rendered: list[str] = []
    for fragment in fragments:
        closure = f'"{" | ".join(fragment.bound_closure)}"'
        metadata = (
            f"adapter__: ClassVar[pydantic.TypeAdapter[{fragment.model_name}]] = "
            f"pydantic.TypeAdapter({fragment.model_name})"
        )
        match fragment:
            case CollectedFactoryFragment():
                base = f"slots.GQLFragment[{fragment.model_name}, {closure}]"
                applied_base = f"{fragment.on_type}[{fragment.model_name}, {closure}]"
                applied_body = indent_block(_render_applied_init(fragment), "    ")
                applied_class = (
                    f"@final\nclass {fragment.applied_class_name}({applied_base}):"
                    f"\n    {applied_body}"
                )
                definition_parts = [metadata, _render_public_fragment_init(fragment)]
                if any(
                    isinstance(arg, CollectedOmittableFragmentArg)
                    for arg in fragment.arg_vars
                ):
                    definition_parts.append(
                        "_omitted__: ClassVar[slots.Omitted] = slots.OMITTED"
                    )
                definition_parts.append(_render_with_args(fragment))
                definition_body = indent_block("\n\n".join(definition_parts), "    ")
                definition_class = (
                    f"@final\nclass {fragment.class_name}({base}):"
                    f"\n    {definition_body}"
                )
                rendered.append(f"{definition_class}\n\n\n{applied_class}")
            case CollectedPlainFragment():
                base = f"{fragment.on_type}[{fragment.model_name}, {closure}]"
                definition_body = indent_block(
                    f"{metadata}\n\n{_render_public_fragment_init(fragment)}", "    "
                )
                definition_class = (
                    f"@final\nclass {fragment.class_name}({base}):"
                    f"\n    {definition_body}"
                )
                rendered.append(definition_class)
    return rendered


def render_gql_fn(
    operations: list[CollectedOperation],
    fragments: list[CollectedFragment],
    templates: list[CollectedTemplate],
    gql_fn_name: str,
    passthrough_texts: tuple[str, ...],
) -> str:
    definition_type = "slots.GQLFragment[pydantic.BaseModel, Any]"
    # Fragment definition и template не являются GQLOperation. Если функция
    # может вернуть один из этих типов, catch-all overload обязан его включить,
    # иначе literal overload окажется вне return type и пересечётся с ним.
    # Catch-all расширяется только видами артефактов, которые есть в пакете;
    # без definitions и templates `gql(some_variable)` сохраняет узкий тип.
    # GQLOperation leads unconditionally: a passthrough statement returns one
    # even in a package whose every typed statement is a fragment.
    return_type = " | ".join(
        dict.fromkeys([
            "runtime.GQLOperation",
            *([definition_type] if fragments else []),
            *(["runtime.GQLTemplate"] if templates else []),
        ])
    )

    def overload_line(literal: str, returned: str) -> str:
        signature = f"def {gql_fn_name}(stmt: Literal[{literal}]) -> {returned}: ..."
        return f"@overload\n{signature}"

    overloads = "\n".join([
        *(
            overload_line(repr(text), operation.class_name)
            for operation in operations
            for text in operation.stmt_texts
        ),
        *(
            overload_line(repr(text), fragment.class_name)
            for fragment in fragments
            for text in fragment.stmt_texts
        ),
        *(
            overload_line(repr(text), template.class_name)
            for template in templates
            for text in template.stmt_texts
        ),
        # Passthrough statements return the plain runtime.GQLOperation the
        # lookup actually builds for them, pinned by their own Literal
        # overloads: появление definition в пакете расширяет только
        # catch-all, not these call sites.
        *(
            overload_line(repr(text), "runtime.GQLOperation")
            for text in passthrough_texts
        ),
        f"@overload\ndef {gql_fn_name}(stmt: str) -> {return_type}: ...",
    ])
    # Every discovered statement maps to the same operation: construct the
    # value `gql()` returns. Fragment classes keep their inherited constructor
    # signature, so a lambda states the zero-argument factory contract directly
    # instead of erasing it through a cast.
    factory_entries = [
        *(
            f"    {text!r}: {operation.class_name},"
            for operation in operations
            for text in operation.stmt_texts
        ),
        *(
            f"    {text!r}: lambda: {fragment.class_name}(),"
            for fragment in fragments
            for text in fragment.stmt_texts
        ),
        *(
            f"    {text!r}: {template.class_name},"
            for template in templates
            for text in template.stmt_texts
        ),
        *(f"    {text!r}: runtime.GQLOperation," for text in passthrough_texts),
    ]
    factories = "\n".join([
        f"_statement_factories: dict[str, Callable[[], {return_type}]] = {{",
        *factory_entries,
        "}",
    ])
    implementation = "\n".join([
        f"def {gql_fn_name}(stmt: str) -> {return_type}:",
        "    if stmt not in _statement_factories:",
        f'        msg = "unknown GraphQL statement passed to {gql_fn_name}; "',
        '        msg += "the generator only discovers bare-name calls with a "',
        '        msg += "single string literal - check the call site, then "',
        '        msg += "regenerate the package"',
        "        raise LookupError(msg)",
        "    return _statement_factories[stmt]()",
    ])
    return f"{overloads}\n\n\n{factories}\n\n\n{implementation}"


def render_package(
    mode: GenerationMode,
    base_url_ref: ImportRef,
    gql_fn_name: str,
    collected: CollectedPackageIR,
    scalars: dict[str, ImportRef],
    to_camel_ref: ImportRef,
) -> str:
    mode_config = RENDER_MODES[mode]
    # Slot node base нужен только generated slot models. Open base создаётся,
    # если model валидируется внутри slot или fragment subtree. Template всегда
    # содержит хотя бы один slot, поэтому его models уже задают
    # `uses_slot_models`.
    uses_slot_models = next(slot_roots(collected.result_artifacts), None) is not None
    uses_open_models = bool(collected.open_model_names)
    uses_on_type_bases = bool(collected.on_type_bases)
    sections = [
        # Slot model — единственная multi-base форма generated module.
        # Fragment definition всегда наследует ровно один on-type base.
        render_header(unsafe_multiple_inheritance=uses_slot_models),
        render_imports(to_camel_ref, scalars, base_url_ref, mode_config),
        render_client_init(base_url_ref, to_camel_ref, mode_config),
        OPEN_BASE if uses_open_models else "",
        SLOT_BASE if uses_slot_models else "",
        "\n".join(render_enums(collected.enums)),
        "\n\n\n".join(
            render_artifacts(collected.result_artifacts, collected.open_model_names)
        ),
        "\n\n\n".join(render_artifacts(collected.input_artifacts, frozenset())),
        "\n\n\n".join(render_operations(collected.operations, mode_config)),
        # The bases precede the fragment classes that derive from them:
        # `from __future__ import annotations` (the header) only defers
        # *annotations*, never a class statement's own base-list expression,
        # so `class ImageParts(OnImageAttachment[...])` still evaluates
        # `OnImageAttachment` eagerly and needs it already bound by then. The
        # closure argument itself never has this problem -- it is a plain
        # string literal, not resolved by the runtime at all.
        ON_TYPE_TYPEVARS if uses_on_type_bases else "",
        "\n\n\n".join(render_on_type_bases(collected.on_type_bases)),
        "\n\n\n".join(render_fragments(collected.fragments)),
        "\n\n\n".join(render_template_bases(collected.templates, mode_config)),
        "\n\n\n".join(render_templates(collected.templates, collected.bindings)),
        render_gql_fn(
            collected.operations,
            collected.fragments,
            collected.templates,
            gql_fn_name,
            collected.passthrough_texts,
        ),
    ]
    return "\n\n\n".join(section for section in sections if section)


def render_artifacts(
    artifacts: list[CollectedArtifact], open_model_names: frozenset[str]
) -> list[str]:
    rendered: list[str] = []
    for artifact in artifacts:
        match artifact:
            case CollectedModel(slot_name=None):
                base = (
                    OPEN_MODEL_BASE_NAME
                    if artifact.name in open_model_names
                    else MODEL_BASE_NAME
                )
                rendered.append(render_pydantic_class(artifact, base))
            case CollectedModel():
                rendered.append(render_slot_class(artifact))
            case CollectedUnionAlias():
                params = (
                    f"[{', '.join(artifact.type_params)}]"
                    if artifact.type_params
                    else ""
                )
                rendered.append(f"type {artifact.name}{params} = {artifact.type_expr}")
    return rendered


def _execute_signature(variables: tuple[CollectedOperationVar, ...]) -> str:
    parts = [var.signature_part for var in variables]
    return ", ".join(["self", *(["*", *parts] if parts else [])])


def _variables_expr(
    variables: tuple[CollectedOperationVar, ...], *extra_entries: str
) -> str:
    entries = [var.variable_entry for var in variables]
    return "{" + ", ".join([*entries, *extra_entries]) + "}"


def _render_execute(
    *,
    result_type: str,
    is_subscription: bool,
    variables: tuple[CollectedOperationVar, ...],
    source_expr: str,
    variables_expr: str,
    extra_kwargs: tuple[str, ...] = (),
    mode: ModeConfig,
) -> str:
    # The one `execute` emitter: a plain operation and a template's shared base
    # differ only in where the document text comes from, what fills `variables`
    # and whether a validation context rides along -- never in how a
    # subscription is shaped or which client method answers it.
    await_kw = "" if is_subscription else mode.await_kw
    client_method = "subscribe" if is_subscription else "query"
    body = "\n".join([
        f"return {await_kw}_client.{client_method}(",
        f"    {result_type},",
        f"    {source_expr},",
        f"    variables={variables_expr},",
        "    headers=self.headers,",
        *(f"    {kwarg}," for kwarg in extra_kwargs),
        ")",
    ])
    return _render_execute_signature(
        result_type=result_type,
        is_subscription=is_subscription,
        variables=variables,
        mode=mode,
        body=body,
    )


def _render_execute_signature(
    *,
    result_type: str,
    is_subscription: bool,
    variables: tuple[CollectedOperationVar, ...],
    mode: ModeConfig,
    body: str,
    decorator: str = "",
) -> str:
    # A subscription's execute hands back the context manager the client
    # returns, so it is never awaited and never declared async in either mode.
    if is_subscription:
        async_kw = ""
        return_type = f"{mode.stream_context}[{mode.generator}[{result_type}]]"
    else:
        async_kw = mode.async_kw
        return_type = result_type
    signature_line = (
        f"{async_kw}def execute({_execute_signature(variables)}) -> {return_type}:"
    )
    lines = [*([decorator] if decorator else []), signature_line]
    return "\n".join([*lines[:-1], f"{lines[-1]}\n    {indent_block(body, '    ')}"])


def render_operations(
    operations: list[CollectedOperation], mode: ModeConfig
) -> list[str]:
    rendered: list[str] = []
    for operation in operations:
        execute = _render_execute(
            result_type=operation.result_type,
            is_subscription=operation.is_subscription,
            variables=operation.variables,
            source_expr=repr(operation.exec_source),
            variables_expr=_variables_expr(operation.variables),
            mode=mode,
        )
        rendered.append(
            "\n".join([
                f"class {operation.class_name}(runtime.GQLOperation):",
                f"    # See: {', '.join(operation.locations)}",
                f"    {indent_block(execute, '    ')}",
            ])
        )
    return rendered


def render_template_bases(
    templates: list[CollectedTemplate], mode: ModeConfig
) -> list[str]:
    # One concrete class per template, shared by every combination of it --
    # `exec_source` и `slot_readers` больше не закреплены за class. `bind()`
    # (`_bind_impl`) задаёт их для instance через
    # `runtime.GQLBoundOperation.bound__`.
    #
    # The parameter is still the *result*, kept generic for the same reason it
    # always was: the slot phantoms live on the models (see
    # `collect.parametrize_slot_paths`) and each `bind()` overload fills them
    # in when it names its own combination's result type
    # (`{Op}Bound[{Op}Result[...]]`, `_bind_signature`), so a helper
    # generic over `{Operation}Bound[TResult]` still hands its caller back the
    # exact result its own binding promised. What changed is that one runtime
    # class now answers for every one of those promises: `execute`'s body can
    # only pass pydantic *one* concrete class per template (bare
    # `{Op}Result`, every phantom at its `Never` default -- confirmed safe by
    # `test_slots_runtime.py`, since a phantom is never a field), so `TResult`
    # gets a `pydantic.BaseModel` bound (required by `client.query`) and meets
    # that one class through a single `cast`. The static promise and the
    # runtime value are reconciled at exactly that line, nowhere else -- do
    # not "fix" the cast by trying to thread the real parametrisation through
    # at runtime, there is no runtime value to thread: every phantom already
    # defaults to `Never` and does not appear in a single field.
    rendered: list[str] = []
    for template in templates:
        header = (
            f"class {template.bound_base_name}"
            f"[{BOUND_RESULT_PARAM}: pydantic.BaseModel]"
            "(runtime.GQLBoundOperation):"
        )
        body = _render_template_bound_execute(template, mode)
        rendered.append(f"{header}\n    {indent_block(body, '    ')}")
    return rendered


def _render_template_bound_execute(
    template: CollectedTemplate, mode: ModeConfig
) -> str:
    await_kw = "" if template.is_subscription else mode.await_kw
    client_method = "subscribe" if template.is_subscription else "query"
    variables_expr = _variables_expr(template.variables, "**self.fragment_args")
    # The single point named in the class-level comment above: the runtime
    # value pydantic actually validates against is the template's own bare
    # result class (every phantom at its `Never` default), while the method's
    # declared return type stays `TResult` -- the parametrisation a caller's
    # own `bind()` overload promised. `cast` reconciles the two; nothing here
    # checks that they agree, because nothing at runtime could.
    query_type_expr = (
        f'typing.cast("type[{BOUND_RESULT_PARAM}]", {template.result_type})'
    )
    body = "\n".join([
        f"return {await_kw}_client.{client_method}(",
        f"    {query_type_expr},",
        "    self.exec_source,",
        f"    variables={variables_expr},",
        "    headers=self.headers,",
        "    slot_readers=self.slot_readers,",
        ")",
    ])
    return _render_execute_signature(
        result_type=BOUND_RESULT_PARAM,
        is_subscription=template.is_subscription,
        variables=template.variables,
        mode=mode,
        body=body,
    )


def _tuple_literal(items: tuple[str, ...]) -> str:
    if not items:
        return "()"
    if len(items) == 1:
        return f"({items[0]},)"
    return f"({', '.join(items)})"


def _slot_reader_spec_expr(readable: CollectedReadableFragment) -> str:
    typenames = ", ".join(repr(name) for name in readable.typenames)
    definition_class = readable.fragment.class_name
    return f"({definition_class}, frozenset({{{typenames}}}))"


def _bound_spec_readers_expr(binding: CollectedBinding) -> str:
    # Полный readable set шире `direct_fragments`: fragment, достигнутый через
    # root-level spread другого fragment, тоже передаётся в `validate_slot__`
    # для независимого чтения и boundary validation. Каждый reader хранит
    # typenames, на которых он достижим. Ключом служит wire name slot, то есть
    # response key из `slot_name__`, поскольку этот dict напрямую становится
    # `self.slot_readers` и попадает в validation context.
    entries = ", ".join(
        f'"{bslot.slot.name}": '
        + _tuple_literal(
            tuple(
                _slot_reader_spec_expr(readable)
                for readable in bslot.readable_fragments
            )
        )
        for bslot in binding.slots
    )
    return "{" + entries + "}"


def _bound_spec_expr(binding: CollectedBinding) -> str:
    return f"({binding.exec_source!r}, {_bound_spec_readers_expr(binding)})"


def _binding_key_expr(binding: CollectedBinding) -> str:
    slot_entries = tuple(
        f"({binding_slot.slot.python_name!r}, "
        + _tuple_literal(
            tuple(
                fragment.binding_class_name
                for fragment in sorted(
                    binding_slot.direct_fragments,
                    key=lambda fragment: fragment.binding_class_name,
                )
            )
        )
        + ")"
        for binding_slot in sorted(
            binding.slots, key=lambda binding_slot: binding_slot.slot.python_name
        )
        if binding_slot.direct_fragments
    )
    return _tuple_literal(slot_entries)


def _render_binding_specs(bindings: list[CollectedBinding]) -> str:
    def entry(binding: CollectedBinding) -> str:
        # Where the row comes from, the same way an operation carries its own
        # (`render_operations`): a combination no longer names a class a
        # comment can sit inside, and most rows are nobody's call site --
        # those name the template and fragment statements the schema built
        # them from, and the ones a `.bind(...)` really wrote name that line
        # (`ir.CollectedBinding.locations`).
        return "\n".join([
            f"    # See: {', '.join(binding.locations)}",
            f"    {_binding_key_expr(binding)}: {_bound_spec_expr(binding)},",
        ])

    entries = "\n".join(entry(binding) for binding in bindings)
    return (
        "_binding_specs: ClassVar[dict[slots.BindingKey, runtime.BoundSpec]] = {\n"
        f"{entries}\n"
        "}"
    )


@dataclass(kw_only=True, frozen=True)
class BindTypeParameter:
    name: str
    declaration: str
    origin: str


@dataclass(kw_only=True, frozen=True)
class _SlotForm:
    # Одна из форм argument `bind()` для одного slot. Overloads образуют
    # декартово произведение этих форм по slots template, поэтому каждый slot
    # независимо выбирает свою форму.
    param: str  # the parameter's annotation
    default: str  # "" or " = ()"
    offered: str  # what this slot's phantom is filled with in the result
    # PEP 695 parameters, объявленные annotation этой формы, и module-level
    # names, на которые annotation ссылается. Структура сохраняется, чтобы
    # naming проверял те же concrete signatures, которые пишет renderer;
    # обратный parsing текста создал бы вторую модель сигнатуры.
    type_params: tuple[BindTypeParameter, ...]
    references: tuple[str, ...]
    # Степень заполнения для порядка overloads: сначала самая узкая форма.
    # Empty sequence, один bindable fragment и fixed-length tuple не имеют общих
    # values, поэтому resolution не зависит от этого порядка.
    weight: int


EMPTY_SLOT_FORM = _SlotForm(
    # Единственное value `Sequence[Never]` — empty sequence, поэтому annotation
    # одинаково принимает `slot=()`, `slot=[]` и omission через default. `Never`
    # делает node статически нечитаемым и соответствует runtime-ошибке для
    # definition, которого binding не предложил.
    param="Sequence[Never]",
    default=" = ()",
    offered="Never",
    type_params=(),
    references=(),
    weight=0,
)


def slot_type_param_names(slot: CollectedTemplateSlot) -> tuple[str, str]:
    # One pair per slot, not one pair per `bind()`: a multi-slot overload
    # filling two slots from two bases has to solve two independent models and
    # two independent closures. Named off the same `field_name_to_pascal` as
    # `slot_param_name`, so `naming._signature_claims`'s check on that one
    # name covers two *slots* whose Pascal spelling collides -- rejected there
    # before either is written here. Not underscore-prefixed, and imported by
    # `naming._bind_signature_type_param_claims`, for the other half of that check:
    # a *fragment* spelled like one of these names, which nothing about the
    # slots' own uniqueness catches.
    suffix = field_name_to_pascal(slot.python_name)
    return f"TModel{suffix}", f"TReads{suffix}"


# (template name, slot keyword) -> arity -> constraints для одной позиции tuple
# этой arity. Каждая запись — readable closure одного fragment; позиция
# разрешается в тот closure, чей fragment передал caller. Closure остаётся
# tuple имён: renderer собирает annotation, а naming читает те же имена.
type SlotTupleFills = dict[tuple[str, str], dict[int, tuple[tuple[str, ...], ...]]]


def _slot_forms(
    template_name: str,
    slot: CollectedTemplateSlot,
    literal_forms: SlotTupleFills,
) -> list[_SlotForm]:
    # {nothing} ∪ {каждый совместимый со slot on-type base} ∪ {каждый
    # multi-fragment tuple, записанный для него literal bind}.
    #
    # Используется base, а не перечисление fragment classes: так generic helper
    # может передать в `bind` fragment, имени которого он не знает. Phantom
    # хранит base и closure caller; `TReads` переносит root-level spreads
    # concrete definition.
    model_param, reads_param = slot_type_param_names(slot)
    base_forms = [
        _SlotForm(
            param=f"{base}[{model_param}, {reads_param}]",
            default="",
            offered=f"{base}[{model_param}, {reads_param}] | {reads_param}",
            type_params=(
                BindTypeParameter(
                    name=model_param,
                    declaration=f"{model_param}: pydantic.BaseModel",
                    origin=f"the bind() type parameter of slot '{slot.name}'",
                ),
                BindTypeParameter(
                    name=reads_param,
                    declaration=reads_param,
                    origin=f"the bind() type parameter of slot '{slot.name}'",
                ),
            ),
            references=(base,),
            weight=1,
        )
        for base in slot.on_type_bases
    ]
    # A multi-fragment slot has no bare spelling: one bare value cannot stand
    # for several fragments, and no single base's parameters could carry them.
    # One form per arity, in arity order, so the overloads stay deterministic.
    fills = literal_forms.get((template_name, slot.python_name), {})
    tuple_forms = [
        _tuple_slot_form(slot, arity, fills[arity]) for arity in sorted(fills)
    ]
    return [EMPTY_SLOT_FORM, *base_forms, *tuple_forms]


def slot_tuple_param_names(slot: CollectedTemplateSlot, arity: int) -> tuple[str, ...]:
    # One PEP 695 parameter per position of a literal tuple form, named off
    # the same Pascal spelling as `slot_type_param_names` and claimed the same
    # way (`naming._bind_signature_type_param_claims`): a fragment spelled like one of
    # these would be shadowed inside the very constraints meant to name it.
    suffix = field_name_to_pascal(slot.python_name)
    return tuple(f"TFill{suffix}{position}" for position in range(1, arity + 1))


def _tuple_slot_form(
    slot: CollectedTemplateSlot,
    arity: int,
    constraints: tuple[tuple[str, ...], ...],
) -> _SlotForm:
    # One form per arity, whatever combinations of that arity the slot's binds
    # wrote: a constrained type parameter per position, each solving to the
    # readable closure of whichever fragment was passed there.
    #
    # The length is the whole point. A `Sequence` fixes none, so
    # `Sequence[ImageParts | LinkParts]` is inhabited by `[image_parts]` just
    # as much as by both, and that one-element call came back typed as
    # offering `LinkParts` -- which the binding it actually reaches never
    # bound, so `LinkParts.read(...)` type-checked and raised `ValueError`.
    # Narrowing a sequence by writing a form per sub-list does not work
    # either: the sub-list's form is subsumed by the full one and returns a
    # different result type, which is `reportOverlappingOverload`.
    #
    # Neither of the two ways to spell the positions concretely works, and
    # each fails at its own scale. A union of every permutation of one
    # combination is exact and factorial: eight fragments in one literal bind
    # wrote 40 320 tuples into one annotation, a 2.5 MB module CPython then
    # refused to compile at all (`RecursionError`), which no
    # `MAX_COMBINATIONS_PER_TEMPLATE` catches because the blowup lives in the
    # annotation, not in the binding specs. Widening each position to the
    # whole combination is linear and *overlapping*: two combinations of one
    # slot sharing a fragment -- (A, B) and (A, C) -- both admit `(A, A)`
    # while returning their own combination's phantom, and
    # `reportOverlappingOverload` on the generated module is a failure of the
    # contract that the output type-checks under this repo's own settings.
    #
    # A constrained parameter is linear, order-free and exact at once, because
    # a constrained type variable solves to the constraint the argument
    # matched, not to the argument's own type: passing `image_parts` binds the
    # position to `ImageParts | <its closure>`, so the phantom is assembled
    # from what the caller actually passed rather than from what some
    # combination holds. One form per arity therefore covers every combination
    # of that arity with nothing left to overlap -- and what it admits beyond
    # them (a repeat, a pair drawn from two different tuples of the slot)
    # reaches the documented `LookupError`, loud, at the call, and never a
    # wrong request.
    names = slot_tuple_param_names(slot, arity)
    constrained = ", ".join(" | ".join(closure) for closure in constraints)
    return _SlotForm(
        param=f"tuple[{', '.join(names)}]",
        default="",
        offered=" | ".join(names),
        type_params=tuple(
            BindTypeParameter(
                name=name,
                declaration=f"{name}: ({constrained})",
                origin=(
                    f"the bind() type parameter of position {position} "
                    f"of slot '{slot.name}'"
                ),
            )
            for position, name in enumerate(names, 1)
        ),
        references=tuple(
            dict.fromkeys(name for closure in constraints for name in closure)
        ),
        weight=arity,
    )


# A slot filled by one fragment is accepted through that fragment's on-type
# base, so a tuple form is only ever needed from this many fragments up -- the
# arity at which no single base can carry the phantom any more.
TUPLE_FORM_MIN_FRAGMENTS = 2


def _literal_tuple_forms(bindings: list[CollectedBinding]) -> SlotTupleFills:
    # Only the multi-fragment slots: a slot filled by one fragment is already
    # accepted through its on-type base, which carries the caller's own model
    # and closure rather than pinning one class.
    #
    # Keyed by the template too, not the slot keyword alone: two templates
    # routinely share a python name for their own slot (the same field name
    # on two different root types, say), and their slots' types -- and so
    # their readable sets -- have nothing to do with each other. A slot-only
    # key let one template's tuple form become an overload on a template whose
    # binding specs never held that combination, a phantom wider than the
    # runtime it describes; `template.name`, not `class_name`, because that
    # is the one of the two `_dedup_statements` has already made injective
    # (see `ir.CollectedTemplate.name`).
    #
    # Collected per arity rather than per combination, because that is the
    # granularity a form has: the positions are constrained parameters, so one
    # form answers every combination of its arity, and two combinations of one
    # slot are two rows of the binding specs rather than two signatures. What
    # they contribute here is their fragments, unioned -- a fragment written
    # in some tuple of this slot is a fragment some position of that arity may
    # hold. A dict keyed by the constraint rather than a list plus a
    # membership test: the deduplication is then a property of the structure
    # instead of a branch that only some packages ever take.
    #
    # `bound_closure`, not the bare class name: a position solves to the
    # constraint it matched, and that constraint is what the phantom is
    # assembled from -- so it has to be everything a bind naming this fragment
    # offers, the fragment itself (its applied class, for a factory) plus what
    # it spreads at its own root level. That is the same closure a solo bind's
    # phantom carries through the base form's `TReads`, so the two spellings
    # of one slot answer alike.
    fills: dict[tuple[str, str], dict[int, dict[tuple[str, ...], None]]] = {}
    for binding in bindings:
        for binding_slot in binding.slots:
            fragments = binding_slot.direct_fragments
            if len(fragments) < TUPLE_FORM_MIN_FRAGMENTS:
                continue
            key = (binding.template.name, binding_slot.slot.python_name)
            constraints = fills.setdefault(key, {}).setdefault(len(fragments), {})
            for fragment in fragments:
                constraints[fragment.bound_closure] = None
    return {
        key: {arity: tuple(constraints) for arity, constraints in by_arity.items()}
        for key, by_arity in fills.items()
    }


def _bind_shapes(
    template: CollectedTemplate,
    tuple_forms: SlotTupleFills,
) -> list[tuple[_SlotForm, ...]]:
    # Все формы `bind()` для template, от самой узкой. `sorted` стабилен,
    # поэтому формы равного weight сохраняют порядок `_slot_forms`: bases по
    # алфавиту, затем tuple forms по arity.
    return sorted(
        itertools.product(
            *(_slot_forms(template.name, slot, tuple_forms) for slot in template.slots)
        ),
        key=lambda shape: sum(form.weight for form in shape),
    )


def _bind_signature(template: CollectedTemplate, shape: tuple[_SlotForm, ...]) -> str:
    params = ", ".join(
        f"{slot.python_name}: {form.param}{form.default}"
        for slot, form in zip(template.slots, shape, strict=True)
    )
    declared = [
        type_param.declaration for form in shape for type_param in form.type_params
    ]
    generic = f"[{', '.join(declared)}]" if declared else ""
    offered = ", ".join(form.offered for form in shape)
    result = f"{template.bound_base_name}[{template.result_type}[{offered}]]"
    return f"def bind{generic}(self, *, {params}) -> {result}:"


@dataclass(kw_only=True, frozen=True)
class BindSignature:
    source: str
    type_params: tuple[BindTypeParameter, ...]
    references: tuple[str, ...]


def bind_signatures(
    template: CollectedTemplate, bindings: list[CollectedBinding]
) -> tuple[BindSignature, ...]:
    # Единое представление overload set для rendering и namespace validation.
    # References дедуплицируются: два упоминания global class в одной signature
    # являются двумя использованиями имени, а не competing declarations.
    tuple_forms = _literal_tuple_forms(bindings)
    return tuple(
        BindSignature(
            source=_bind_signature(template, shape),
            type_params=tuple(
                type_param for form in shape for type_param in form.type_params
            ),
            references=tuple(
                dict.fromkeys((
                    template.bound_base_name,
                    template.result_type,
                    *(name for form in shape for name in form.references),
                ))
            ),
        )
        for shape in _bind_shapes(template, tuple_forms)
    )


# The "no such combination" diagnostic `_bind_impl`'s body raises, written
# from inside an `if ... is None:` block at 4-space (function-body) indent.
#
# One expression, binding no local: every name a rendered body binds joins the
# enclosing method's keyword namespace, where a GraphQL name that happens to
# snake to it would collide -- and `naming._signature_claims` would then have
# to reserve it, which is a second, hand-maintained copy of what this function
# writes. The generated module suppresses formatting and linting wholesale
# (see `render_header`), so the length of the one line this produces is
# nobody's business but this comment's.
def _bind_lookup_error_line(template_class_name: str) -> str:
    # Two ways to land here, and naming only the first one sent the second
    # after a fix that changes nothing: the combination may well be written,
    # on a call the scan cannot read (a base that is an expression rather than
    # a name, `TEMPLATES["q"].bind(...)`). Such a call is recorded with its
    # reason in `ignored_binds.json` under `debug_path`, which is where the
    # difference between the two is legible.
    message = (
        f"unknown bind combination for {template_class_name}; single-fragment "
        "and empty combinations are generated from the schema, so this is a "
        "tuple combination no call site writes literally - write it, then "
        "regenerate the package. A call whose template is an expression the "
        "scan cannot follow is never read either: those are listed, with the "
        "reason, in the debug run's ignored_binds.json"
    )
    return f'        raise LookupError("{message}")'


def _bind_impl(template: CollectedTemplate, signature: str) -> str:
    # Implementation под overload stubs перечисляет slots template вместо
    # `**fragments`, поэтому interpreter сразу отвергает неизвестный keyword.
    # Иначе empty value под опечатанным именем исчезло бы в `binding_key` и
    # совпало с комбинацией без fragments.
    fragments_dict = ", ".join(
        f"{slot.python_name!r}: {slot.python_name}" for slot in template.slots
    )
    binding_key_expr = f"slots.binding_key({{{fragments_dict}}})"
    # Переданные caller fragments нормализуются в tuple на slot через
    # `slots.as_bindable_fragments` и становятся аргументом `passed` метода
    # `bound__`. Wire name slot нужен для diagnostics конфликтующих
    # applications; сами readers создаются только из definition classes в spec.
    passed_dict = ", ".join(
        f"{slot.name!r}: slots.as_bindable_fragments({slot.python_name})"
        for slot in template.slots
    )
    # The lookup is written twice rather than kept in a local: a local joins
    # this method's keyword namespace, where a slot that snakes to the same
    # spelling would land on it (see `_bind_lookup_error_line`). It did -- a
    # `cls` local took the parameter of a slot called `cls`, and the module
    # still ran, because the key is built before the name is rewritten, while
    # a type checker read the rest of the body against the parameter's type.
    # The specs are a dict, so the second lookup costs a hash.
    receiver = f"{template.bound_base_name}[{template.result_type}]"
    spec_arg = f"self._binding_specs[{binding_key_expr}]"
    return "\n".join([
        signature,
        f"    if {binding_key_expr} not in self._binding_specs:",
        _bind_lookup_error_line(template.class_name),
        f"    return {receiver}.bound__(",
        f"        {spec_arg}, {{{passed_dict}}},",
        "    )",
    ])


def _bind_impl_signature(template: CollectedTemplate) -> str:
    # The signature under the stubs, deliberately wider than any of them: a
    # call the stubs reject still has to reach the binding lookup, where the
    # documented `LookupError` names the missing combination -- a `TypeError`
    # from the interpreter would say the parameter had the wrong type, which
    # is not what is wrong.
    fragment_type = "slots.GQLBindableFragment[pydantic.BaseModel, Any]"
    params = ", ".join(
        f"{slot.python_name}: {fragment_type} | Sequence[{fragment_type}] = ()"
        for slot in template.slots
    )
    return f"def bind(self, *, {params}) -> runtime.GQLBoundOperation:"


# (name, what claims it) for every name a rendered method body reads from an
# enclosing scope. Declared here, beside the bodies that read them, and
# consumed by `naming._signature_claims`, which reserves each against a
# GraphQL name that happens to snake to it -- a second hand-maintained list
# over there would go stale the day a body reads one more name. No body binds
# a local of its own (see `_bind_lookup_error_line`), so a method's namespace
# is its parameters and these.
#
# A module-scope claim alone covers the wrong collision: module scope is where
# two *bindings* fight, while a parameter shadows the name only inside the one
# body that reads it. Nothing constrains `to_snake_fn`'s output to a spelling
# these cannot take: it is a documented hook, and the identity function is a
# legal one to pass.
# Each list comes in two halves. The fixed half holds every name a body of
# that kind reads whatever the schema is -- the imported modules, the package's
# own dicts, a builtin -- so it can be computed for a rendered module with no
# IR to hand, which is what `tests.corpus.generated_oracles` checks the
# rendered bodies against. The other half names generated classes, and a class
# is claimed against the one scope whose body reaches for it.
def bind_body_fixed_names() -> tuple[tuple[str, str], ...]:
    return (
        ("slots", "the iron_gql slots module"),
        # A builtin is as shadowable as a module-scope name, and this body
        # raises one (`_bind_lookup_error_line`).
        ("LookupError", "the builtin raised for an unknown combination"),
    )


def bind_body_free_names(template: CollectedTemplate) -> tuple[tuple[str, str], ...]:
    return (
        *bind_body_fixed_names(),
        (template.bound_base_name, f"the bound base of template '{template.name}'"),
        (template.result_type, f"the result class of template '{template.name}'"),
    )


def operation_execute_fixed_names() -> tuple[tuple[str, str], ...]:
    return (("_client", "the generated client binding"),)


def operation_execute_free_names(result_type: str) -> tuple[tuple[str, str], ...]:
    return (
        *operation_execute_fixed_names(),
        (result_type, "the result class this execute() validates against"),
    )


def template_execute_fixed_names() -> tuple[tuple[str, str], ...]:
    # A template's `execute` lives on the shared bound base, which reaches for
    # the typing module on top of what a plain operation's body reads.
    return (
        *operation_execute_fixed_names(),
        ("typing", "the standard-library typing module"),
    )


def template_execute_free_names(
    template: CollectedTemplate,
) -> tuple[tuple[str, str], ...]:
    return (
        *template_execute_fixed_names(),
        (template.result_type, "the result class this execute() validates against"),
    )


def applied_init_body_fixed_names() -> tuple[tuple[str, str], ...]:
    return (("super", "the built-in super() function"),)


def with_args_body_free_names(
    fragment: CollectedFactoryFragment,
) -> tuple[tuple[str, str], ...]:
    return ((fragment.applied_class_name, "the applied fragment class"),)


def fragment_init_body_free_names(
    fragment: CollectedFragment,
) -> tuple[tuple[str, str], ...]:
    return ((fragment.class_name, "the fragment definition class"),)


def method_body_fixed_names() -> frozenset[str]:
    # Every schema-independent name some generated method body reads, together.
    # The oracle over a rendered module checks against this whole set rather
    # than per scope: it reads the module's symbol table, which says which
    # names a body reaches for but not which artifact wrote the body.
    return frozenset(
        name
        for name, _origin in (
            *bind_body_fixed_names(),
            *template_execute_fixed_names(),
            *applied_init_body_fixed_names(),
        )
    )


def render_templates(
    templates: list[CollectedTemplate],
    bindings: list[CollectedBinding],
) -> list[str]:
    # The bare per-template binder: one `@overload` per way a call can be
    # spelled, over one implementation. The signatures say what `bind()`
    # accepts; the implementation answers every call the same way, by looking
    # the combination up.
    rendered: list[str] = []
    for template in templates:
        template_bindings = [
            binding for binding in bindings if binding.template.name == template.name
        ]
        signatures = bind_signatures(template, template_bindings)
        if len(signatures) == 1:
            # Nothing in the package can be spread into any of this
            # template's slots, so the only call `bind()` accepts is the empty
            # one -- and one signature is not an overload set. Written as the
            # implementation's own signature: `@overload` needs at least two
            # stubs, and inventing a second one that no call can reach would
            # be a signature standing for nothing.
            body = _bind_impl(template, signatures[0].source)
        else:
            stubs = [f"@overload\n{signature.source} ..." for signature in signatures]
            body = "\n".join([
                *stubs,
                _bind_impl(template, _bind_impl_signature(template)),
            ])
        header = f"class {template.class_name}(runtime.GQLTemplate):"
        class_body = "\n\n".join((
            _render_binding_specs(template_bindings),
            body,
        ))
        rendered.append(f"{header}\n    {indent_block(class_body, '    ')}")
    return rendered


def render_enums(enums: list[CollectedEnum]) -> list[str]:
    return [
        f"type {enum.name} = Literal[{', '.join(repr(value) for value in enum.values)}]"
        for enum in enums
    ]
