from itertools import starmap

from iron_gql.codegen.ir import CollectedArtifact
from iron_gql.codegen.ir import CollectedEnum
from iron_gql.codegen.ir import CollectedField
from iron_gql.codegen.ir import CollectedModel
from iron_gql.codegen.ir import CollectedOperation
from iron_gql.codegen.ir import CollectedPackageIR
from iron_gql.codegen.ir import CollectedUnionAlias
from iron_gql.codegen.ir import ImportRef
from iron_gql.codegen.ir import render_type_expr
from iron_gql.codegen.util import indent_block

HEADER = """\
from __future__ import annotations
# Code generated by iron_gql, DO NOT EDIT.
# fmt: off
# pyright: reportUnusedImport=false
# ruff: noqa"""


# The module-level names the scaffold binds, kept in one place because
# `scaffold_claims` hands the same set to the collision rule and everything
# below renders from these very names. Each tuple is already sorted: the import
# blocks are emitted in this order.
MODEL_BASE_NAME = "GQLModel"
BASE_CLASS_NAMES = (MODEL_BASE_NAME,)
STDLIB_MODULE_NAMES = ("datetime",)
# Imported unconditionally and referenced by every model, so it is reserved
# unconditionally too — deriving the claim from `to_camel_ref` instead would
# drop it as soon as a package points that option somewhere other than pydantic.
THIRD_PARTY_MODULE_NAMES = ("pydantic",)
CONTEXTLIB_NAMES = ("AbstractAsyncContextManager",)
ABC_NAMES = ("AsyncGenerator",)
TYPING_NAMES = ("Annotated", "Literal", "overload")
IRON_GQL_NAMES = ("runtime",)


def scaffold_claims(
    *,
    package_name: str,
    gql_fn_name: str,
    base_url_ref: ImportRef,
    scalars: dict[str, ImportRef],
    to_camel_ref: ImportRef,
) -> dict[str, tuple[str, ...]]:
    # Names only imported when a package uses optional features are listed
    # unconditionally: the reserved set must not depend on which of them a
    # package happens to use today, or a new statement could rebind a name
    # that generated fine a commit earlier.
    #
    # Each binding keeps its origin so the collision rule can tell two
    # scaffold sources fighting over one name apart from one binding listed
    # twice: identical origins (the same import statement reached from two
    # configs, e.g. `import pydantic`) collapse into a single claim, while
    # different origins for one name are a real collision.
    pairs: list[tuple[str, str]] = [
        *((name, "the generated model base class") for name in BASE_CLASS_NAMES),
        *((module, f"import {module}") for module in STDLIB_MODULE_NAMES),
        *((module, f"import {module}") for module in THIRD_PARTY_MODULE_NAMES),
        *((name, f"from contextlib import {name}") for name in CONTEXTLIB_NAMES),
        *((name, f"from collections.abc import {name}") for name in ABC_NAMES),
        *((name, f"from typing import {name}") for name in TYPING_NAMES),
        *((name, f"from iron_gql import {name}") for name in IRON_GQL_NAMES),
        (gql_fn_name, "the generated gql function"),
        (f"{package_name.upper()}_CLIENT", "the generated client binding"),
        (f"_{package_name.upper()}_GQL_DISPATCH", "the generated dispatch dict"),
        (
            f"_{package_name.upper()}_GQL_PASSTHROUGH",
            "the generated passthrough set",
        ),
        (base_url_ref.root_symbol, base_url_ref.import_statement()),
        (to_camel_ref.root_module, f"import {to_camel_ref.root_module}"),
        *((ref.root_module, f"import {ref.root_module}") for ref in scalars.values()),
    ]
    claims: dict[str, dict[str, None]] = {}
    for name, origin in pairs:
        claims.setdefault(name, {})[origin] = None
    return {name: tuple(origins) for name, origins in claims.items()}


def render_field(field: CollectedField) -> str:
    rendered_type = render_type_expr(field.rendered_type)
    default_expr = field.default_expr
    if field.is_conditional and default_expr is None:
        default_expr = "None"

    if field.alias is not None:
        rendered_type = (
            f"Annotated[{rendered_type}, "
            f'pydantic.Field(validation_alias="{field.alias}", '
            f'serialization_alias="{field.alias}")]'
        )
    if default_expr is not None:
        return f"{field.name}: {rendered_type} = {default_expr}"
    return f"{field.name}: {rendered_type}"


def render_pydantic_class(name: str, base: str, fields: list[CollectedField]) -> str:
    rendered_fields = "\n".join(render_field(field) for field in fields)
    return f"class {name}({base}):\n    {indent_block(rendered_fields, '    ')}"


def render_imports(
    to_camel_ref: ImportRef,
    scalars: dict[str, ImportRef],
    base_url_ref: ImportRef,
) -> str:
    import_modules = [ref.module for ref in scalars.values()]
    scalar_imports = "\n".join(f"import {module}" for module in import_modules)
    stdlib_imports = "\n".join(f"import {module}" for module in STDLIB_MODULE_NAMES)
    abc_imports = "\n".join(f"from collections.abc import {name}" for name in ABC_NAMES)
    contextlib_imports = "\n".join(
        f"from contextlib import {name}" for name in CONTEXTLIB_NAMES
    )
    typing_imports = "\n".join(f"from typing import {name}" for name in TYPING_NAMES)
    third_party_imports = "\n".join(
        f"import {module}" for module in THIRD_PARTY_MODULE_NAMES
    )
    iron_gql_imports = "\n".join(
        f"from iron_gql import {name}" for name in IRON_GQL_NAMES
    )
    return f"""\
{stdlib_imports}
{abc_imports}
{contextlib_imports}
{typing_imports}

{third_party_imports}

{iron_gql_imports}

import {to_camel_ref.module}

{scalar_imports}

{base_url_ref.import_statement()}"""


def render_client_init(
    package_name: str,
    base_url_ref: ImportRef,
    to_camel_ref: ImportRef,
) -> str:
    return f"""\
{package_name.upper()}_CLIENT = runtime.GQLClient(
    base_url={base_url_ref.symbol},
)


class {MODEL_BASE_NAME}(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True,
        serialize_by_alias=True,
        alias_generator=pydantic.AliasGenerator(
            validation_alias={to_camel_ref.dotted_path},
            serialization_alias={to_camel_ref.dotted_path},
        ),
        extra="forbid",
        validate_default=True,
    )"""


def render_gql_fn(
    operations: list[CollectedOperation],
    package_name: str,
    gql_fn_name: str,
    passthrough_texts: tuple[str, ...],
) -> str:
    dict_name = f"_{package_name.upper()}_GQL_DISPATCH"
    passthrough_name = f"_{package_name.upper()}_GQL_PASSTHROUGH"
    entries = [
        (repr(text), operation.class_name)
        for operation in operations
        for text in operation.stmt_texts
    ]

    def overload_line(literal: str, returned: str) -> str:
        signature = f"def {gql_fn_name}(stmt: Literal[{literal}]) -> {returned}: ..."
        return f"@overload\n{signature}"

    overloads = "\n".join([
        *starmap(overload_line, entries),
        # Passthrough statements return the plain runtime.GQLOperation the
        # lookup actually builds for them, pinned by their own Literal
        # overloads.
        *(
            overload_line(repr(text), "runtime.GQLOperation")
            for text in passthrough_texts
        ),
        f"@overload\ndef {gql_fn_name}(stmt: str) -> runtime.GQLOperation: ...",
    ])
    dict_entries = "\n".join(
        f"    {literal}: {returned}," for literal, returned in entries
    )
    sections = [
        overloads,
        "\n".join([
            f"{dict_name}: dict[str, type[runtime.GQLOperation]] = {{",
            dict_entries,
            "}",
        ]),
    ]

    lookup_lines = [
        f"    query_cls = {dict_name}.get(stmt)",
        "    if query_cls is not None:",
        "        return query_cls()",
    ]
    if passthrough_texts:
        # Known statements nothing typed — fragment definitions spread into
        # operations by name. Their call sites legitimately receive the
        # untyped catch-all; only a statement the generator has never seen
        # raises.
        sections.append(
            "\n".join([
                f"{passthrough_name}: frozenset[str] = frozenset({{",
                "\n".join(f"    {text!r}," for text in passthrough_texts),
                "})",
            ])
        )
        lookup_lines.extend([
            f"    if stmt in {passthrough_name}:",
            "        return runtime.GQLOperation()",
        ])

    sections.append(
        "\n".join([
            f"def {gql_fn_name}(stmt: str) -> runtime.GQLOperation:",
            *lookup_lines,
            f'    msg = "unknown GraphQL statement passed to {gql_fn_name}; "',
            '    msg += "the generator only discovers bare-name calls with a "',
            '    msg += "single string literal - check the call site, then "',
            '    msg += "regenerate the package"',
            "    raise LookupError(msg)",
        ])
    )
    return "\n\n\n".join(sections)


def render_package(
    base_url_ref: ImportRef,
    package_name: str,
    gql_fn_name: str,
    collected: CollectedPackageIR,
    scalars: dict[str, ImportRef],
    to_camel_ref: ImportRef,
    passthrough_texts: tuple[str, ...] = (),
) -> str:
    sections = [
        HEADER,
        render_imports(
            to_camel_ref,
            scalars,
            base_url_ref,
        ),
        render_client_init(package_name, base_url_ref, to_camel_ref),
        "\n".join(render_enums(collected.enums)),
        "\n\n\n".join(render_artifacts(collected.result_artifacts)),
        "\n\n\n".join(render_artifacts(collected.input_artifacts)),
        "\n\n\n".join(render_operations(collected.operations, package_name)),
        render_gql_fn(
            collected.operations, package_name, gql_fn_name, passthrough_texts
        ),
    ]
    return "\n\n\n".join(section for section in sections if section)


def render_artifacts(artifacts: list[CollectedArtifact]) -> list[str]:
    rendered: list[str] = []
    for artifact in artifacts:
        match artifact:
            case CollectedModel():
                rendered.append(
                    render_pydantic_class(artifact.name, "GQLModel", artifact.fields)
                )
            case CollectedUnionAlias():
                rendered.append(f"type {artifact.name} = {artifact.type_expr}")
    return rendered


def render_operations(
    operations: list[CollectedOperation],
    package_name: str,
) -> list[str]:
    rendered: list[str] = []
    for operation in operations:
        see_comment = f"# See: {', '.join(operation.locations)}"
        signature = ", ".join(operation.signature_parts)
        if operation.is_subscription:
            async_kw, await_kw = "", ""
            return_type = (
                f"AbstractAsyncContextManager[AsyncGenerator[{operation.result_type}]]"
            )
        else:
            async_kw, await_kw = "async ", "await "
            return_type = operation.result_type
        rendered.append(
            f"""
class {operation.class_name}(runtime.GQLOperation):
    {see_comment}
    {async_kw}def execute({signature}) -> {return_type}:
        return {await_kw}{package_name.upper()}_CLIENT.{operation.client_method}(
            {operation.result_type},
            {operation.exec_source!r},
            variables={operation.variables_expr},
            headers=self.headers,
        )
""".strip()
        )
    return rendered


def render_enums(enums: list[CollectedEnum]) -> list[str]:
    return [
        f"type {enum.name} = Literal[{', '.join(repr(value) for value in enum.values)}]"
        for enum in enums
    ]
