from __future__ import annotations
# Code generated by iron_gql, DO NOT EDIT.
# fmt: off
# pyright: reportUnusedImport=false
# ruff: noqa


import datetime
from typing import Annotated
from typing import Literal
from typing import overload

import pydantic

from iron_gql import runtime

import pydantic.alias_generators

import builtins

from myapp.config import GRAPHQL_URL


API_CLIENT = runtime.GQLClient(
    base_url=GRAPHQL_URL,
)


class GQLModel(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True,
        alias_generator=pydantic.alias_generators.to_camel,
        extra="forbid",
        validate_default=True,
    )


type Role = Literal['ADMIN', 'MEMBER']


class CreateUserResultCreateUser(GQLModel):
    id: builtins.str
    name: str
    email: str
    role: Role


class CreateUserResult(GQLModel):
    create_user: CreateUserResultCreateUser


class FindUserResultFindUser(GQLModel):
    id: builtins.str
    name: str
    email: str


class FindUserResult(GQLModel):
    find_user: FindUserResultFindUser | None


class GetProfileResultUser(GQLModel):
    id: builtins.str
    name: str
    email: str | None = None
    phone: str | None = None
    role: Role


class GetProfileResult(GQLModel):
    user: GetProfileResultUser | None


class GetUserResultUserPosts(GQLModel):
    id: builtins.str
    title: str


class GetUserResultUser(GQLModel):
    id: builtins.str
    name: str
    email: str
    phone: str
    role: Role
    posts: list[GetUserResultUserPosts]


class GetUserResult(GQLModel):
    user: GetUserResultUser | None


class SearchResultSearchPostAuthor(GQLModel):
    name: str


class SearchResultSearchPost(GQLModel):
    typename__: Literal["Post"] = pydantic.Field(alias="__typename")
    id: builtins.str
    title: str
    author: SearchResultSearchPostAuthor


class SearchResultSearchUser(GQLModel):
    typename__: Literal["User"] = pydantic.Field(alias="__typename")
    id: builtins.str
    name: str
    role: Role


type SearchResultSearch = Annotated[SearchResultSearchPost | SearchResultSearchUser, pydantic.Field(discriminator="typename__")]


class SearchResult(GQLModel):
    search: list[SearchResultSearch]


class CreateUserInput(GQLModel):
    name: str
    email: str
    role: Role


class FindUserById(GQLModel):
    id: builtins.str


class FindUserByEmail(GQLModel):
    email: str


type FindUserBy = FindUserById | FindUserByEmail


class CreateUser(runtime.GQLQuery):
    async def execute(self, *, input: CreateUserInput) -> CreateUserResult:
        return await API_CLIENT.query(
            CreateUserResult,
            'mutation CreateUser($input: CreateUserInput!) {\n  createUser(input: $input) {\n    id\n    name\n    email\n    role\n  }\n}',
            {"input": runtime.serialize_var(input)},
            headers=self.headers,
            upload_files=self.upload_files,
        )


class FindUser(runtime.GQLQuery):
    async def execute(self, *, by: FindUserBy) -> FindUserResult:
        return await API_CLIENT.query(
            FindUserResult,
            'query FindUser($by: FindUserBy!) {\n  findUser(by: $by) {\n    id\n    name\n    email\n  }\n}',
            {"by": runtime.serialize_var(by)},
            headers=self.headers,
            upload_files=self.upload_files,
        )


class GetProfile(runtime.GQLQuery):
    async def execute(self, *, id: builtins.str, with_email: bool, skip_phone: bool) -> GetProfileResult:
        return await API_CLIENT.query(
            GetProfileResult,
            'query GetProfile($id: ID!, $withEmail: Boolean!, $skipPhone: Boolean!) {\n  user(id: $id) {\n    id\n    name\n    email @include(if: $withEmail)\n    phone @skip(if: $skipPhone)\n    role\n  }\n}',
            {"id": runtime.serialize_var(id), "withEmail": runtime.serialize_var(with_email), "skipPhone": runtime.serialize_var(skip_phone)},
            headers=self.headers,
            upload_files=self.upload_files,
        )


class GetUser(runtime.GQLQuery):
    async def execute(self, *, id: builtins.str) -> GetUserResult:
        return await API_CLIENT.query(
            GetUserResult,
            'query GetUser($id: ID!) {\n  user(id: $id) {\n    ...UserFields\n    posts {\n      id\n      title\n    }\n  }\n}\n\nfragment UserFields on User {\n  id\n  name\n  email\n  phone\n  role\n}',
            {"id": runtime.serialize_var(id)},
            headers=self.headers,
            upload_files=self.upload_files,
        )


class Search(runtime.GQLQuery):
    async def execute(self, *, query: str) -> SearchResult:
        return await API_CLIENT.query(
            SearchResult,
            'query Search($query: String!) {\n  search(query: $query) {\n    __typename\n    ... on User {\n      id\n      name\n      role\n    }\n    ... on Post {\n      id\n      title\n      author {\n        name\n      }\n    }\n  }\n}',
            {"query": runtime.serialize_var(query)},
            headers=self.headers,
            upload_files=self.upload_files,
        )


@overload
def api_gql(stmt: Literal['\n        mutation CreateUser($input: CreateUserInput!) {\n            createUser(input: $input) {\n                id\n                name\n                email\n                role\n            }\n        }\n    ']) -> CreateUser: ...
@overload
def api_gql(stmt: Literal['\n        query FindUser($by: FindUserBy!) {\n            findUser(by: $by) {\n                id\n                name\n                email\n            }\n        }\n    ']) -> FindUser: ...
@overload
def api_gql(stmt: Literal['\n        query GetProfile($id: ID!, $withEmail: Boolean!, $skipPhone: Boolean!) {\n            user(id: $id) {\n                id\n                name\n                email @include(if: $withEmail)\n                phone @skip(if: $skipPhone)\n                role\n            }\n        }\n    ']) -> GetProfile: ...
@overload
def api_gql(stmt: Literal['\n        query GetUser($id: ID!) {\n            user(id: $id) {\n                ...UserFields\n                posts { id title }\n            }\n        }\n\n        fragment UserFields on User {\n            id\n            name\n            email\n            phone\n            role\n        }\n    ']) -> GetUser: ...
@overload
def api_gql(stmt: Literal['\n        query Search($query: String!) {\n            search(query: $query) {\n                __typename\n                ... on User {\n                    id\n                    name\n                    role\n                }\n                ... on Post {\n                    id\n                    title\n                    author { name }\n                }\n            }\n        }\n    ']) -> Search: ...
@overload
def api_gql(stmt: str) -> runtime.GQLQuery: ...


_API_GQL_DISPATCH: dict[str, type[runtime.GQLQuery]] = {
    '\n        mutation CreateUser($input: CreateUserInput!) {\n            createUser(input: $input) {\n                id\n                name\n                email\n                role\n            }\n        }\n    ': CreateUser,
    '\n        query FindUser($by: FindUserBy!) {\n            findUser(by: $by) {\n                id\n                name\n                email\n            }\n        }\n    ': FindUser,
    '\n        query GetProfile($id: ID!, $withEmail: Boolean!, $skipPhone: Boolean!) {\n            user(id: $id) {\n                id\n                name\n                email @include(if: $withEmail)\n                phone @skip(if: $skipPhone)\n                role\n            }\n        }\n    ': GetProfile,
    '\n        query GetUser($id: ID!) {\n            user(id: $id) {\n                ...UserFields\n                posts { id title }\n            }\n        }\n\n        fragment UserFields on User {\n            id\n            name\n            email\n            phone\n            role\n        }\n    ': GetUser,
    '\n        query Search($query: String!) {\n            search(query: $query) {\n                __typename\n                ... on User {\n                    id\n                    name\n                    role\n                }\n                ... on Post {\n                    id\n                    title\n                    author { name }\n                }\n            }\n        }\n    ': Search,
}


def api_gql(stmt: str) -> runtime.GQLQuery:
    query_cls = _API_GQL_DISPATCH.get(stmt)
    if query_cls is not None:
        return query_cls()
    return runtime.GQLQuery()
